// SPDX-License-Identifier: BSD-3-Clause

// Command genaddrs emits tailcat addresses produced by the real Go
// implementation, for cross-checking the C parser and encoder against.
//
// Each line of output is:
//
//	<address> TAB <json description of the ConnInfo it parses back to>
//
// The C side (tests/crosscheck.c) parses each address, re-encodes it, and
// requires the result to be byte-identical. That is a much stronger claim
// than "our own tests agree with themselves": it pins our wire format to
// whatever the Go library actually emits today.
package main

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"math/rand"
	"os"

	"github.com/tailscale/tailcat"
	"tailscale.com/tailcfg"
	"tailscale.com/types/key"
)

var (
	count   = flag.Int("count", 200, "how many random addresses to emit")
	seed    = flag.Int64("seed", 1, "PRNG seed, so runs are reproducible")
	vectors = flag.String("vectors", "",
		"instead of addresses, write tailcat-layer test vectors to this C header")
)

// writeVectors emits tests/meow_vectors.h from the real tailcat package:
// encoded meow packets, and the disco keys tailcat derives from a node key.
// Both are wire-visible, so pinning them against upstream is what stops a
// plausible-but-wrong implementation passing its own tests.
func writeVectors(path string, rnd *rand.Rand) error {
	var b bytes.Buffer
	p := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	p("/* SPDX-License-Identifier: BSD-3-Clause")
	p(" *")
	p(" * GENERATED by tools/genaddrs -vectors -- do not edit.")
	p(" *")
	p(" * Produced with github.com/tailscale/tailcat's own EncodeMeowPing,")
	p(" * EncodeMeowed and DiscoPublicForNode. Regenerate with:")
	p(" *   cd tools/genaddrs && go run . -vectors ../../tests/meow_vectors.h")
	p(" */")
	p("#ifndef TC_MEOW_VECTORS_H_")
	p("#define TC_MEOW_VECTORS_H_")
	p("")

	p("/* Node private key -> the disco public key tailcat derives from it. */")
	p("static const struct {")
	p("\tconst char *node_private, *node_public, *disco_public;")
	p("} kDiscoVectors[] = {")
	privs := make([]key.NodePrivate, 0, 8)
	for i := 0; i < 8; i++ {
		priv := key.NewNode()
		privs = append(privs, priv)
		raw := priv.Raw32()
		pub := priv.Public().Raw32()
		disco := tailcat.DiscoPublicForNode(priv).Raw32()
		p("\t{ %q, %q, %q },", hex.EncodeToString(raw[:]),
			hex.EncodeToString(pub[:]), hex.EncodeToString(disco[:]))
	}
	p("};")
	p("")

	p("/* Encoded meow packets, straight from upstream's encoders. */")
	p("static const struct {")
	p("\tconst char *node_public, *disco_public, *encoded;")
	p("} kMeowPingVectors[] = {")
	for _, priv := range privs {
		pub := priv.Public()
		disco := tailcat.DiscoPublicForNode(priv)
		pkt := tailcat.EncodeMeowPing(pub, disco.DiscoPublic)
		pubRaw := pub.Raw32()
		discoRaw := disco.Raw32()
		p("\t{ %q, %q, %q },", hex.EncodeToString(pubRaw[:]),
			hex.EncodeToString(discoRaw[:]), hex.EncodeToString(pkt))
	}
	p("};")
	p("")

	p("/* The meowed acknowledgment. */")
	p("static const char kMeowedEncoded[] = %q;",
		hex.EncodeToString(tailcat.EncodeMeowed()))
	p("")
	p("#endif /* TC_MEOW_VECTORS_H_ */")

	return os.WriteFile(path, b.Bytes(), 0o644)
}

func randomRegion(rnd *rand.Rand, nodes int) *tailcfg.DERPRegion {
	r := &tailcfg.DERPRegion{
		RegionID:   tailcfg.DERPRegionID(rnd.Intn(1000)),
		RegionCode: fmt.Sprintf("r%d", rnd.Intn(100)),
		RegionName: fmt.Sprintf("Region %d", rnd.Intn(100)),
	}
	for i := 0; i < nodes; i++ {
		n := &tailcfg.DERPNode{
			Name:     fmt.Sprintf("%dx", i),
			RegionID: r.RegionID,
			HostName: fmt.Sprintf("derp%d.example.com", rnd.Intn(1000)),
		}
		switch rnd.Intn(4) {
		case 0:
			n.IPv4 = fmt.Sprintf("10.%d.%d.%d", rnd.Intn(256), rnd.Intn(256), rnd.Intn(256))
		case 1:
			n.IPv6 = "2001:db8::1"
		case 2:
			n.IPv4 = "192.0.2.1"
			n.IPv6 = "2001:db8::2"
		}
		if rnd.Intn(3) == 0 {
			n.STUNPort = rnd.Intn(65536)
		}
		if rnd.Intn(3) == 0 {
			n.DERPPort = rnd.Intn(65536)
		}
		if rnd.Intn(5) == 0 {
			n.InsecureForTests = true
		}
		if rnd.Intn(6) == 0 {
			n.CertName = fmt.Sprintf("cert%d.example.com", rnd.Intn(100))
		}
		// Exercise the "no hostname, so the name survives" branch.
		if rnd.Intn(8) == 0 {
			n.HostName = ""
		}
		r.Nodes = append(r.Nodes, n)
	}
	return r
}

func main() {
	flag.Parse()
	rnd := rand.New(rand.NewSource(*seed))

	if *vectors != "" {
		if err := writeVectors(*vectors, rnd); err != nil {
			fmt.Fprintln(os.Stderr, "genaddrs:", err)
			os.Exit(1)
		}
		fmt.Fprintln(os.Stderr, "genaddrs: wrote", *vectors)
		return
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	for i := 0; i < *count; i++ {
		priv := key.NewNode()
		ci := tailcat.ConnInfo{
			ServerPublic: tailcat.NodePublic{NodePublic: priv.Public()},
		}
		if rnd.Intn(4) != 0 {
			ci.ServerDiscoPublic = tailcat.DiscoPublicForNode(priv)
		}
		if rnd.Intn(4) != 0 {
			ci.PresharedKey = tailcat.NewPresharedKey()
		}
		// Either an embedded region or a bare region ID, matching how real
		// addresses are built.
		if rnd.Intn(2) == 0 {
			ci.Region = []*tailcfg.DERPRegion{randomRegion(rnd, 1+rnd.Intn(4))}
		} else {
			ci.RegionID = tailcfg.DERPRegionID(rnd.Intn(1000))
		}

		addr := ci.Addr()

		// Emit the form the address actually parses back to, so the C side
		// compares against the restored fields rather than the inputs.
		back, err := tailcat.ParseAddr(addr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "genaddrs: own address failed to parse: %v\n", err)
			os.Exit(1)
		}
		j, err := json.Marshal(back)
		if err != nil {
			fmt.Fprintf(os.Stderr, "genaddrs: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(w, "%s\t%s\n", addr, j)
	}
}
