/* SPDX-License-Identifier: BSD-3-Clause
 *
 * A one-shot SSH server, for interoperating with a real OpenSSH client.
 *
 * This is the test that settles what none of the offline ones can. The packet
 * layer's vectors were generated by Go code written from the same OpenSSH
 * document as our C, so a misreading of that document would have been
 * reproduced faithfully on both sides and every check would still pass --
 * swapping K_1 and K_2 in both, for instance. Only a peer that was written
 * from neither can tell us whether we actually speak the protocol.
 *
 * So: listen on a port, serve exactly one connection, and let
 * `ssh -i key user@localhost <command>` be the judge. If the key exchange,
 * the cipher, the signature, the authentication and the channel are all right
 * the client prints what we wrote and exits zero. If any one of them is
 * wrong, it does not.
 *
 * Usage: livesshd <port> <host-seed-hex> <authorized-key-hex> [dropbox-dir]
 *
 * With a directory, the `sftp` subsystem is served as a write-only drop box
 * and real `sftp` and `scp` become the clients.
 */

#include "tc/dropbox.h"
#include "tc/sshserver.h"

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

/* Decoded a nibble at a time rather than with sscanf("%2x").
 *
 * This is bug 7 in the README, reintroduced in a new file and found the same
 * way: cosmo's sscanf does not honour that field width reliably, so a key
 * decodes correctly under glibc and wrongly under cosmocc. The symptom was
 * the same too -- everything up to the point where a key has to match works
 * perfectly, because the host key is not checked by a client told not to
 * check it, and only the authorized key fails.
 *
 * The lesson is that the fix for bug 7 lived inside the file that had it. */
static int unhex1(char c)
{
	if (c >= '0' && c <= '9')
		return c - '0';
	if (c >= 'a' && c <= 'f')
		return c - 'a' + 10;
	if (c >= 'A' && c <= 'F')
		return c - 'A' + 10;
	return -1;
}

static int unhex(const char *s, uint8_t *out, size_t want)
{
	if (strlen(s) != want * 2)
		return -1;
	for (size_t i = 0; i < want; i++) {
		int hi = unhex1(s[i * 2]), lo = unhex1(s[i * 2 + 1]);
		if (hi < 0 || lo < 0)
			return -1;
		out[i] = (uint8_t)(hi << 4 | lo);
	}
	return 0;
}

static int sock_read(void *ctx, uint8_t *buf, size_t cap, size_t *nread)
{
	int fd = *(int *)ctx;
	ssize_t n = read(fd, buf, cap);
	if (n < 0)
		return TC_ERR_CLOSED;
	if (n == 0)
		return TC_ERR_CLOSED;
	*nread = (size_t)n;
	return TC_OK;
}

static int sock_write(void *ctx, const uint8_t *buf, size_t len)
{
	int fd = *(int *)ctx;
	size_t off = 0;
	while (off < len) {
		ssize_t n = write(fd, buf + off, len - off);
		if (n <= 0)
			return TC_ERR_CLOSED;
		off += (size_t)n;
	}
	return TC_OK;
}

/* on_start accepts an exec or a subsystem and says something back.
 *
 * Deliberately not an echo: the client must see bytes that could only have
 * come from a server that got this far, so the script can tell "the channel
 * worked" from "the client printed its own input back at itself". */
static const char *g_dropbox_dir;

/* serve_sftp opens the drop box and hands it to the shared serving loop.
 * The framing lives in tc_dropbox_serve so the CLI and this test run the
 * same code rather than two copies of the same loop. */
static int serve_sftp(tc_ssh_server *s)
{
	tc_dropbox db;
	int rc = tc_dropbox_open(&db, g_dropbox_dir);
	if (rc != TC_OK) {
		fprintf(stderr, "livesshd: drop box %s unusable\n", g_dropbox_dir);
		return rc;
	}
	rc = tc_dropbox_serve(&db, s);
	fprintf(stderr, "livesshd: drop box received %u files, %llu bytes\n",
	        db.files, (unsigned long long)db.bytes);
	return rc;
}

static int on_start(void *ctx, tc_ssh_server *s, tc_ssh_request_type type,
                    const char *arg)
{
	(void)ctx;

	if (type == TC_SSH_REQ_SUBSYSTEM && strcmp(arg, "sftp") == 0) {
		if (g_dropbox_dir == NULL) {
			fprintf(stderr, "livesshd: no drop box configured\n");
			return TC_ERR_UNSUPPORTED;
		}
		int srv = serve_sftp(s);
		if (srv != TC_OK)
			fprintf(stderr, "livesshd: sftp failed: %s\n", tc_strerror(srv));
		return srv;
	}
	char line[512];
	int n = snprintf(line, sizeof line, "tailcat-c ssh subset: %s %s\n",
	                 type == TC_SSH_REQ_SUBSYSTEM ? "subsystem" : "exec", arg);
	if (n < 0)
		return TC_ERR_INVAL;

	int rc = tc_ssh_server_write(s, line, (size_t)n);
	if (rc != TC_OK)
		return rc;

	/* Read whatever the client sends until it is done, and echo the byte
	 * count -- which exercises the receive path and the window, not just the
	 * send path. */
	size_t total = 0;
	for (;;) {
		uint8_t buf[4096];
		size_t got = 0;
		rc = tc_ssh_server_read(s, buf, sizeof buf, &got);
		if (rc == TC_ERR_DONE || rc == TC_ERR_CLOSED)
			break;
		if (rc != TC_OK)
			return rc;
		total += got;
	}

	/* The rekey count goes back to the client so the script can require that
	 * one actually happened. A transfer that merely succeeded proves nothing
	 * about rekeying if the peer never asked for one. */
	n = snprintf(line, sizeof line, "received %zu bytes after %u rekeys\n",
	             total, tc_ssh_server_rekeys(s));
	if (n > 0)
		(void)tc_ssh_server_write(s, line, (size_t)n);

	(void)tc_ssh_server_exit(s, 0);
	return TC_OK;
}

int main(int argc, char **argv)
{
	if (argc != 4 && argc != 5) {
		fprintf(stderr, "usage: livesshd <port> <host-seed-hex> "
		                "<authorized-hex> [dropbox-dir]\n");
		return 2;
	}
	if (argc == 5)
		g_dropbox_dir = argv[4];
	int port = atoi(argv[1]);
	uint8_t seed[32], authorized[32];
	if (unhex(argv[2], seed, sizeof seed) != 0 ||
	    unhex(argv[3], authorized, 32) != 0) {
		fprintf(stderr, "livesshd: bad hex\n");
		return 2;
	}

	int ls = socket(AF_INET, SOCK_STREAM, 0);
	if (ls < 0) {
		perror("socket");
		return 1;
	}
	int one = 1;
	(void)setsockopt(ls, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);

	struct sockaddr_in addr;
	memset(&addr, 0, sizeof addr);
	addr.sin_family = AF_INET;
	addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
	addr.sin_port = htons((uint16_t)port);
	if (bind(ls, (struct sockaddr *)&addr, sizeof addr) != 0) {
		perror("bind");
		return 1;
	}
	if (listen(ls, 1) != 0) {
		perror("listen");
		return 1;
	}
	/* The script waits for this line rather than sleeping, so a slow machine
	 * does not turn into a flaky test. */
	printf("listening %d\n", port);
	fflush(stdout);

	int fd = accept(ls, NULL, NULL);
	if (fd < 0) {
		perror("accept");
		return 1;
	}
	close(ls);

	tc_ssh_server_opts opts;
	memset(&opts, 0, sizeof opts);
	opts.host_seed = seed;
	opts.authorized = authorized;
	opts.num_authorized = 1;
	opts.read = sock_read;
	opts.write = sock_write;
	opts.io_ctx = &fd;
	opts.on_start = on_start;

	int rc = tc_ssh_server_run(&opts);
	close(fd);

	if (rc != TC_OK && rc != TC_ERR_CLOSED) {
		fprintf(stderr, "livesshd: session failed: %s\n", tc_strerror(rc));
		return 1;
	}
	fprintf(stderr, "livesshd: session complete\n");
	return 0;
}
