/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Vectors come from tests/crypto_vectors.h, generated by tools/genvectors
 * from the same Go libraries WireGuard uses. Two of them (rfc7693-abc and
 * rfc7748-1) are the published RFC values, so the generator itself is
 * anchored to something external.
 */

#include "tc/crypto.h"
#include "tc/noise.h"
#include "tctest.h"

#include "crypto_vectors.h"

/* ---- hex helper ------------------------------------------------------ */

static int hexval(char c)
{
	if (c >= '0' && c <= '9')
		return c - '0';
	if (c >= 'a' && c <= 'f')
		return c - 'a' + 10;
	if (c >= 'A' && c <= 'F')
		return c - 'A' + 10;
	return -1;
}

/* unhex decodes a hex string into buf and returns its byte length, or
 * SIZE_MAX on malformed input or overflow. */
static size_t unhex(uint8_t *buf, size_t cap, const char *s)
{
	size_t n = strlen(s);
	if (n % 2 != 0 || n / 2 > cap)
		return (size_t)-1;
	for (size_t i = 0; i < n; i += 2) {
		int hi = hexval(s[i]), lo = hexval(s[i + 1]);
		if (hi < 0 || lo < 0)
			return (size_t)-1;
		buf[i / 2] = (uint8_t)(hi << 4 | lo);
	}
	return n / 2;
}

#define MAXBUF 2048
static uint8_t b_msg[MAXBUF], b_key[MAXBUF], b_want[MAXBUF];
static uint8_t b_a[MAXBUF], b_b[MAXBUF], b_c[MAXBUF], b_out[MAXBUF + 64];

/* ---- BLAKE2s --------------------------------------------------------- */

static void test_blake2s(void)
{
	for (size_t i = 0; i < sizeof kBlake2sVectors / sizeof kBlake2sVectors[0];
	     i++) {
		const char *name = kBlake2sVectors[i].name;
		TCT_CASE(name);

		size_t msg_len = unhex(b_msg, MAXBUF, kBlake2sVectors[i].msg);
		size_t key_len = unhex(b_key, MAXBUF, kBlake2sVectors[i].key);
		size_t want_len = unhex(b_want, MAXBUF, kBlake2sVectors[i].want);
		size_t outlen = (size_t)kBlake2sVectors[i].outlen;

		TCT_TRUE(msg_len != (size_t)-1 && key_len != (size_t)-1);
		TCT_EQ_INT(want_len, outlen);

		/* One-shot. */
		uint8_t got[TC_BLAKE2S_HASH_LEN];
		tc_blake2s(got, outlen, b_msg, msg_len,
		           key_len ? b_key : NULL, key_len);
		TCT_EQ_MEM(got, b_want, outlen);

		/* Incremental, one byte at a time. This is what catches a wrong
		 * final-block flag: the buffered block must not be compressed until
		 * we know no more data follows. */
		tc_blake2s_ctx ctx;
		tc_blake2s_init_key(&ctx, outlen, key_len ? b_key : NULL, key_len);
		for (size_t j = 0; j < msg_len; j++)
			tc_blake2s_update(&ctx, b_msg + j, 1);
		uint8_t got2[TC_BLAKE2S_HASH_LEN];
		tc_blake2s_final(&ctx, got2);
		TCT_EQ_MEM(got2, b_want, outlen);

		/* Incremental in awkward chunk sizes, straddling block boundaries. */
		const size_t chunks[] = { 1, 7, 63, 64, 65, 127, 128 };
		for (size_t ci = 0; ci < sizeof chunks / sizeof chunks[0]; ci++) {
			tc_blake2s_init_key(&ctx, outlen, key_len ? b_key : NULL, key_len);
			size_t off = 0;
			while (off < msg_len) {
				size_t take = chunks[ci];
				if (take > msg_len - off)
					take = msg_len - off;
				tc_blake2s_update(&ctx, b_msg + off, take);
				off += take;
			}
			uint8_t got3[TC_BLAKE2S_HASH_LEN];
			tc_blake2s_final(&ctx, got3);
			TCT_EQ_MEM(got3, b_want, outlen);
		}

		/* Zero-length updates must be no-ops. */
		tc_blake2s_init_key(&ctx, outlen, key_len ? b_key : NULL, key_len);
		tc_blake2s_update(&ctx, NULL, 0);
		tc_blake2s_update(&ctx, b_msg, msg_len);
		tc_blake2s_update(&ctx, NULL, 0);
		uint8_t got4[TC_BLAKE2S_HASH_LEN];
		tc_blake2s_final(&ctx, got4);
		TCT_EQ_MEM(got4, b_want, outlen);
	}

	TCT_CASE("final wipes the context");
	tc_blake2s_ctx ctx;
	uint8_t out[TC_BLAKE2S_HASH_LEN];
	tc_blake2s_init(&ctx, TC_BLAKE2S_HASH_LEN);
	tc_blake2s_update(&ctx, "secret", 6);
	tc_blake2s_final(&ctx, out);
	TCT_TRUE(tc_ct_is_zero(&ctx, sizeof ctx));
}

/* ---- HMAC-BLAKE2s ---------------------------------------------------- */

static void test_hmac(void)
{
	for (size_t i = 0;
	     i < sizeof kHmacBlake2sVectors / sizeof kHmacBlake2sVectors[0]; i++) {
		TCT_CASE(kHmacBlake2sVectors[i].name);

		size_t key_len = unhex(b_key, MAXBUF, kHmacBlake2sVectors[i].key);
		size_t in0_len = unhex(b_a, MAXBUF, kHmacBlake2sVectors[i].in0);
		size_t in1_len = unhex(b_b, MAXBUF, kHmacBlake2sVectors[i].in1);
		size_t want_len = unhex(b_want, MAXBUF, kHmacBlake2sVectors[i].want);
		TCT_EQ_INT(want_len, TC_BLAKE2S_HASH_LEN);

		uint8_t got[TC_BLAKE2S_HASH_LEN];
		tc_hmac_blake2s(got, key_len ? b_key : NULL, key_len,
		                in0_len ? b_a : NULL, in0_len,
		                in1_len ? b_b : NULL, in1_len);
		TCT_EQ_MEM(got, b_want, TC_BLAKE2S_HASH_LEN);
	}

	TCT_CASE("HMAC is not keyed BLAKE2s");
	/* These are different constructions. Confusing them would still produce
	 * plausible-looking output but would not interoperate, so assert they
	 * genuinely differ. */
	uint8_t key[32], msg[32], a[32], b[32];
	memset(key, 0xab, sizeof key);
	memset(msg, 0xcd, sizeof msg);
	tc_hmac_blake2s(a, key, sizeof key, msg, sizeof msg, NULL, 0);
	tc_blake2s(b, sizeof b, msg, sizeof msg, key, sizeof key);
	TCT_TRUE(memcmp(a, b, 32) != 0);
}

/* ---- WireGuard KDF --------------------------------------------------- */

static void test_kdf(void)
{
	for (size_t i = 0; i < sizeof kKdfVectors / sizeof kKdfVectors[0]; i++) {
		TCT_CASE(kKdfVectors[i].name);

		size_t key_len = unhex(b_key, MAXBUF, kKdfVectors[i].key);
		size_t in_len = unhex(b_msg, MAXBUF, kKdfVectors[i].input);
		TCT_EQ_INT(key_len, TC_BLAKE2S_HASH_LEN);

		uint8_t t0[32], t1[32], t2[32];
		size_t w0 = unhex(b_a, MAXBUF, kKdfVectors[i].t0);
		size_t w1 = unhex(b_b, MAXBUF, kKdfVectors[i].t1);
		size_t w2 = unhex(b_c, MAXBUF, kKdfVectors[i].t2);
		(void)w1;
		(void)w2;
		TCT_EQ_INT(w0, 32);

		switch (kKdfVectors[i].n) {
		case 1:
			tc_kdf1(t0, b_key, in_len ? b_msg : NULL, in_len);
			TCT_EQ_MEM(t0, b_a, 32);
			break;
		case 2:
			tc_kdf2(t0, t1, b_key, in_len ? b_msg : NULL, in_len);
			TCT_EQ_MEM(t0, b_a, 32);
			TCT_EQ_MEM(t1, b_b, 32);
			break;
		case 3:
			tc_kdf3(t0, t1, t2, b_key, in_len ? b_msg : NULL, in_len);
			TCT_EQ_MEM(t0, b_a, 32);
			TCT_EQ_MEM(t1, b_b, 32);
			TCT_EQ_MEM(t2, b_c, 32);
			break;
		default:
			TCT_FAILF("unexpected KDF arity %d", kKdfVectors[i].n);
			break;
		}
	}

	TCT_CASE("KDF outputs are distinct");
	uint8_t key[32], t0[32], t1[32], t2[32];
	memset(key, 0x11, sizeof key);
	tc_kdf3(t0, t1, t2, key, "x", 1);
	TCT_TRUE(memcmp(t0, t1, 32) != 0);
	TCT_TRUE(memcmp(t1, t2, 32) != 0);
	TCT_TRUE(memcmp(t0, t2, 32) != 0);

	TCT_CASE("KDF1 agrees with KDF2's first output");
	uint8_t a0[32], b0[32], b1[32];
	tc_kdf1(a0, key, "abc", 3);
	tc_kdf2(b0, b1, key, "abc", 3);
	TCT_EQ_MEM(a0, b0, 32);
}

/* ---- X25519 ---------------------------------------------------------- */

static void test_x25519(void)
{
	for (size_t i = 0; i < sizeof kX25519Vectors / sizeof kX25519Vectors[0];
	     i++) {
		TCT_CASE(kX25519Vectors[i].name);

		uint8_t sk[32], pk[32], want[32], got[32];
		TCT_EQ_INT(unhex(sk, sizeof sk, kX25519Vectors[i].scalar), 32);
		TCT_EQ_INT(unhex(pk, sizeof pk, kX25519Vectors[i].point), 32);

		size_t want_len = unhex(want, sizeof want, kX25519Vectors[i].want);
		int rc = tc_x25519(got, sk, pk);

		if (want_len == 0) {
			/* Go reported a low-order point; we must reject it too. */
			TCT_EQ_INT(rc, TC_ERR_INVAL);
		} else {
			TCT_EQ_INT(rc, TC_OK);
			TCT_EQ_MEM(got, want, 32);
		}
	}

	for (size_t i = 0;
	     i < sizeof kX25519BaseVectors / sizeof kX25519BaseVectors[0]; i++) {
		TCT_CASE(kX25519BaseVectors[i].name);
		uint8_t sk[32], want[32], got[32];
		TCT_EQ_INT(unhex(sk, sizeof sk, kX25519BaseVectors[i].sk), 32);
		TCT_EQ_INT(unhex(want, sizeof want, kX25519BaseVectors[i].pk), 32);
		TCT_EQ_INT(tc_x25519_base(got, sk), TC_OK);
		TCT_EQ_MEM(got, want, 32);
	}

	TCT_CASE("small-order public keys are rejected");
	for (size_t i = 0;
	     i < sizeof kX25519LowOrder / sizeof kX25519LowOrder[0]; i++) {
		uint8_t sk[32], pk[32], got[32];
		memset(sk, 0x77, sizeof sk);
		tc_x25519_clamp(sk);
		TCT_EQ_INT(unhex(pk, sizeof pk, kX25519LowOrder[i]), 32);
		TCT_EQ_INT(tc_x25519(got, sk, pk), TC_ERR_INVAL);
		/* And nothing usable is left behind. */
		TCT_TRUE(tc_ct_is_zero(got, sizeof got));
	}

	TCT_CASE("clamping matches WireGuard");
	uint8_t sk[32];
	memset(sk, 0xff, sizeof sk);
	tc_x25519_clamp(sk);
	TCT_EQ_INT(sk[0] & 7, 0);        /* low three bits cleared */
	TCT_EQ_INT(sk[31] & 0x80, 0);    /* top bit cleared */
	TCT_EQ_INT(sk[31] & 0x40, 0x40); /* second-highest bit set */

	TCT_CASE("a generated keypair agrees with itself");
	uint8_t pk[32], pk2[32];
	TCT_EQ_INT(tc_x25519_keypair(sk, pk), TC_OK);
	TCT_EQ_INT(tc_x25519_base(pk2, sk), TC_OK);
	TCT_EQ_MEM(pk, pk2, 32);

	TCT_CASE("Diffie-Hellman agrees in both directions");
	uint8_t ska[32], pka[32], skb[32], pkb[32], ss1[32], ss2[32];
	TCT_EQ_INT(tc_x25519_keypair(ska, pka), TC_OK);
	TCT_EQ_INT(tc_x25519_keypair(skb, pkb), TC_OK);
	TCT_EQ_INT(tc_x25519(ss1, ska, pkb), TC_OK);
	TCT_EQ_INT(tc_x25519(ss2, skb, pka), TC_OK);
	TCT_EQ_MEM(ss1, ss2, 32);
}

/* ---- ChaCha20-Poly1305 ----------------------------------------------- */

static void test_aead(void)
{
	for (size_t i = 0; i < sizeof kAeadVectors / sizeof kAeadVectors[0]; i++) {
		TCT_CASE(kAeadVectors[i].name);

		uint8_t key[32], nonce[12];
		TCT_EQ_INT(unhex(key, sizeof key, kAeadVectors[i].key), 32);
		TCT_EQ_INT(unhex(nonce, sizeof nonce, kAeadVectors[i].nonce), 12);
		size_t ad_len = unhex(b_a, MAXBUF, kAeadVectors[i].ad);
		size_t pt_len = unhex(b_msg, MAXBUF, kAeadVectors[i].pt);
		size_t ct_len = unhex(b_want, MAXBUF, kAeadVectors[i].ct);
		TCT_EQ_INT(ct_len, pt_len + TC_AEAD_TAG_LEN);

		TCT_EQ_INT(tc_aead_seal_nonce(b_out, key, nonce, ad_len ? b_a : NULL,
		                              ad_len, pt_len ? b_msg : NULL, pt_len),
		           TC_OK);
		TCT_EQ_MEM(b_out, b_want, ct_len);

		/* Decrypting the Go-produced ciphertext must give the plaintext. */
		TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce, ad_len ? b_a : NULL,
		                              ad_len, b_want, ct_len),
		           TC_OK);
		if (pt_len != 0)
			TCT_EQ_MEM(b_b, b_msg, pt_len);

		/* Flipping any one bit of the tag, ciphertext or AD must fail. */
		if (ct_len > 0) {
			memcpy(b_c, b_want, ct_len);
			b_c[ct_len - 1] ^= 1; /* tag */
			TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce,
			                              ad_len ? b_a : NULL, ad_len, b_c,
			                              ct_len),
			           TC_ERR_INVAL);
		}
		if (pt_len > 0) {
			memcpy(b_c, b_want, ct_len);
			b_c[0] ^= 1; /* ciphertext */
			TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce,
			                              ad_len ? b_a : NULL, ad_len, b_c,
			                              ct_len),
			           TC_ERR_INVAL);
		}
		if (ad_len > 0) {
			b_a[0] ^= 1;
			TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce, b_a, ad_len,
			                              b_want, ct_len),
			           TC_ERR_INVAL);
			b_a[0] ^= 1;
		}
	}
}

static void test_aead_counter(void)
{
	for (size_t i = 0;
	     i < sizeof kAeadCounterVectors / sizeof kAeadCounterVectors[0]; i++) {
		TCT_CASE(kAeadCounterVectors[i].name);

		uint8_t key[32];
		TCT_EQ_INT(unhex(key, sizeof key, kAeadCounterVectors[i].key), 32);
		size_t ad_len = unhex(b_a, MAXBUF, kAeadCounterVectors[i].ad);
		size_t pt_len = unhex(b_msg, MAXBUF, kAeadCounterVectors[i].pt);
		size_t ct_len = unhex(b_want, MAXBUF, kAeadCounterVectors[i].ct);

		uint64_t ctr = (uint64_t)kAeadCounterVectors[i].counter;

		TCT_EQ_INT(tc_aead_seal(b_out, key, ctr, b_a, ad_len, b_msg, pt_len),
		           TC_OK);
		TCT_EQ_MEM(b_out, b_want, ct_len);

		TCT_EQ_INT(tc_aead_open(b_b, key, ctr, b_a, ad_len, b_want, ct_len),
		           TC_OK);
		TCT_EQ_MEM(b_b, b_msg, pt_len);

		/* A different counter must not authenticate. */
		TCT_EQ_INT(tc_aead_open(b_b, key, ctr ^ 1u, b_a, ad_len, b_want,
		                        ct_len),
		           TC_ERR_INVAL);
	}

	TCT_CASE("open rejects input shorter than the tag");
	uint8_t key[32] = { 0 }, tiny[8] = { 0 };
	TCT_EQ_INT(tc_aead_open(b_b, key, 0, NULL, 0, tiny, sizeof tiny),
	           TC_ERR_INVAL);

	TCT_CASE("in-place encryption works");
	uint8_t k2[32];
	memset(k2, 0x5a, sizeof k2);
	uint8_t inplace[32 + TC_AEAD_TAG_LEN];
	memset(inplace, 0x11, 32);
	uint8_t expect[32 + TC_AEAD_TAG_LEN];
	TCT_EQ_INT(tc_aead_seal(expect, k2, 7, NULL, 0, inplace, 32), TC_OK);
	TCT_EQ_INT(tc_aead_seal(inplace, k2, 7, NULL, 0, inplace, 32), TC_OK);
	TCT_EQ_MEM(inplace, expect, sizeof expect);
}

/* ---- CSPRNG ---------------------------------------------------------- */

static void test_random(void)
{
	TCT_CASE("random init succeeds");
	TCT_EQ_INT(tc_random_init(), TC_OK);

	TCT_CASE("random bytes are not constant");
	uint8_t a[64], b[64];
	TCT_EQ_INT(tc_random_bytes(a, sizeof a), TC_OK);
	TCT_EQ_INT(tc_random_bytes(b, sizeof b), TC_OK);
	TCT_TRUE(memcmp(a, b, sizeof a) != 0);
	TCT_TRUE(!tc_ct_is_zero(a, sizeof a));

	TCT_CASE("zero-length request is fine");
	TCT_EQ_INT(tc_random_bytes(a, 0), TC_OK);

	TCT_CASE("a large request is filled");
	static uint8_t big[70000]; /* larger than MBEDTLS_CTR_DRBG_MAX_REQUEST */
	TCT_EQ_INT(tc_random_bytes(big, sizeof big), TC_OK);
	/* The tail must have been written, not left zero by a short read. */
	TCT_TRUE(!tc_ct_is_zero(big + sizeof big - 64, 64));

	TCT_CASE("null buffer is rejected");
	TCT_EQ_INT(tc_random_bytes(NULL, 8), TC_ERR_INVAL);
}

/* ---- NaCl box, as used by the DERP handshake ------------------------- */

static void test_hsalsa20(void)
{
	for (size_t i = 0; i < sizeof kHSalsa20Vectors / sizeof kHSalsa20Vectors[0];
	     i++) {
		TCT_CASE(kHSalsa20Vectors[i].name);
		uint8_t key[32], in[16], want[32], got[32];
		TCT_EQ_INT(unhex(key, sizeof key, kHSalsa20Vectors[i].key), 32);
		TCT_EQ_INT(unhex(in, sizeof in, kHSalsa20Vectors[i].in), 16);
		TCT_EQ_INT(unhex(want, sizeof want, kHSalsa20Vectors[i].want), 32);
		tc_hsalsa20(got, key, in);
		TCT_EQ_MEM(got, want, 32);
	}
}

static void test_secretbox(void)
{
	for (size_t i = 0;
	     i < sizeof kSecretboxVectors / sizeof kSecretboxVectors[0]; i++) {
		TCT_CASE(kSecretboxVectors[i].name);

		uint8_t key[32], nonce[24];
		TCT_EQ_INT(unhex(key, sizeof key, kSecretboxVectors[i].key), 32);
		TCT_EQ_INT(unhex(nonce, sizeof nonce, kSecretboxVectors[i].nonce), 24);
		size_t pt_len = unhex(b_msg, MAXBUF, kSecretboxVectors[i].pt);
		size_t ct_len = unhex(b_want, MAXBUF, kSecretboxVectors[i].ct);
		TCT_EQ_INT(ct_len, pt_len + TC_BOX_TAG_LEN);

		TCT_EQ_INT(tc_secretbox_seal(b_out, key, nonce,
		                             pt_len ? b_msg : NULL, pt_len),
		           TC_OK);
		TCT_EQ_MEM(b_out, b_want, ct_len);

		TCT_EQ_INT(tc_secretbox_open(b_b, key, nonce, b_want, ct_len), TC_OK);
		if (pt_len)
			TCT_EQ_MEM(b_b, b_msg, pt_len);

		/* Tamper with the tag. */
		memcpy(b_c, b_want, ct_len);
		b_c[0] ^= 1;
		TCT_EQ_INT(tc_secretbox_open(b_b, key, nonce, b_c, ct_len),
		           TC_ERR_INVAL);
	}

	TCT_CASE("secretbox rejects input shorter than the tag");
	uint8_t key[32] = { 0 }, nonce[24] = { 0 }, tiny[8] = { 0 };
	TCT_EQ_INT(tc_secretbox_open(b_b, key, nonce, tiny, sizeof tiny),
	           TC_ERR_INVAL);
}

static void test_box(void)
{
	for (size_t i = 0; i < sizeof kBoxVectors / sizeof kBoxVectors[0]; i++) {
		TCT_CASE(kBoxVectors[i].name);

		uint8_t sk[32], peer_pk[32], nonce[24], shared[32];
		TCT_EQ_INT(unhex(sk, sizeof sk, kBoxVectors[i].sk), 32);
		TCT_EQ_INT(unhex(peer_pk, sizeof peer_pk, kBoxVectors[i].peer_pk), 32);
		TCT_EQ_INT(unhex(nonce, sizeof nonce, kBoxVectors[i].nonce), 24);
		TCT_EQ_INT(unhex(shared, sizeof shared, kBoxVectors[i].shared), 32);
		size_t pt_len = unhex(b_msg, MAXBUF, kBoxVectors[i].pt);
		size_t ct_len = unhex(b_want, MAXBUF, kBoxVectors[i].ct);

		/* Go's box.Seal output here has no nonce prefix (we passed nil), so
		 * it is exactly tag || ciphertext. */
		TCT_EQ_INT(ct_len, pt_len + TC_BOX_TAG_LEN);

		/* The precomputed shared key must match Go's box.Precompute. */
		uint8_t got_shared[32];
		TCT_EQ_INT(tc_box_beforenm(got_shared, sk, peer_pk), TC_OK);
		TCT_EQ_MEM(got_shared, shared, 32);

		TCT_EQ_INT(tc_box_seal(b_out, nonce, pt_len ? b_msg : NULL, pt_len,
		                       peer_pk, sk),
		           TC_OK);
		TCT_EQ_MEM(b_out, b_want, ct_len);

		TCT_EQ_INT(tc_box_open(b_b, nonce, b_want, ct_len, peer_pk, sk),
		           TC_OK);
		if (pt_len)
			TCT_EQ_MEM(b_b, b_msg, pt_len);
	}

	TCT_CASE("box is symmetric between the two peers");
	uint8_t ska[32], pka[32], skb[32], pkb[32], nonce[24];
	TCT_EQ_INT(tc_x25519_keypair(ska, pka), TC_OK);
	TCT_EQ_INT(tc_x25519_keypair(skb, pkb), TC_OK);
	TCT_EQ_INT(tc_random_bytes(nonce, sizeof nonce), TC_OK);

	const char *msg = "derp clientinfo";
	size_t mlen = strlen(msg);
	TCT_EQ_INT(tc_box_seal(b_out, nonce, msg, mlen, pkb, ska), TC_OK);
	TCT_EQ_INT(tc_box_open(b_b, nonce, b_out, mlen + TC_BOX_TAG_LEN, pka, skb),
	           TC_OK);
	TCT_EQ_MEM(b_b, msg, mlen);

	TCT_CASE("box rejects the wrong peer key");
	uint8_t skc[32], pkc[32];
	TCT_EQ_INT(tc_x25519_keypair(skc, pkc), TC_OK);
	TCT_EQ_INT(tc_box_open(b_b, nonce, b_out, mlen + TC_BOX_TAG_LEN, pkc, skb),
	           TC_ERR_INVAL);

	TCT_CASE("box rejects a small-order peer key");
	uint8_t zero[32] = { 0 };
	TCT_EQ_INT(tc_box_seal(b_out, nonce, msg, mlen, zero, ska), TC_ERR_INVAL);
}

/* ---- XChaCha20-Poly1305 ------------------------------------------------ */

static void test_hchacha20(void)
{
	TCT_CASE("HChaCha20 derives the subkey XChaCha needs");
	/* The first vector is draft-irtf-cfrg-xchacha-03's own, so this is
	 * anchored outside the Go library that generated the rest. */
	for (size_t i = 0; i < sizeof kHChaCha20Vectors / sizeof kHChaCha20Vectors[0];
	     i++) {
		uint8_t key[32], nonce[16], want[32], got[32];
		TCT_EQ_INT(unhex(key, sizeof key, kHChaCha20Vectors[i].key), 32);
		TCT_EQ_INT(unhex(nonce, sizeof nonce, kHChaCha20Vectors[i].nonce), 16);
		TCT_EQ_INT(unhex(want, sizeof want, kHChaCha20Vectors[i].want), 32);
		tc_hchacha20(got, key, nonce);
		if (memcmp(got, want, 32) != 0)
			TCT_FAILF("hchacha20 %s", kHChaCha20Vectors[i].name);
		tct_checks++;
	}
}

static void test_xaead(void)
{
	TCT_CASE("XChaCha20-Poly1305 matches x/crypto");
	for (size_t i = 0; i < sizeof kXAeadVectors / sizeof kXAeadVectors[0]; i++) {
		uint8_t key[32], nonce[24];
		static uint8_t ad[MAXBUF], pt[MAXBUF], want[MAXBUF], got[MAXBUF];
		TCT_EQ_INT(unhex(key, sizeof key, kXAeadVectors[i].key), 32);
		TCT_EQ_INT(unhex(nonce, sizeof nonce, kXAeadVectors[i].nonce), 24);
		size_t ad_len = unhex(ad, MAXBUF, kXAeadVectors[i].ad);
		size_t pt_len = unhex(pt, MAXBUF, kXAeadVectors[i].pt);
		size_t want_len = unhex(want, MAXBUF, kXAeadVectors[i].want);

		TCT_EQ_INT(tc_xaead_seal(got, key, nonce, ad, ad_len, pt, pt_len),
		           TC_OK);
		if (memcmp(got, want, want_len) != 0)
			TCT_FAILF("xaead seal %s", kXAeadVectors[i].name);
		tct_checks++;

		static uint8_t back[MAXBUF];
		TCT_EQ_INT(tc_xaead_open(back, key, nonce, ad, ad_len, want, want_len),
		           TC_OK);
		if (pt_len != 0 && memcmp(back, pt, pt_len) != 0)
			TCT_FAILF("xaead open %s", kXAeadVectors[i].name);
		tct_checks++;

		/* A changed tag, a changed nonce and changed additional data must
		 * each break it: an AEAD that only authenticates the ciphertext
		 * would pass the two tests above and still be useless. */
		static uint8_t bad[MAXBUF];
		memcpy(bad, want, want_len);
		bad[want_len - 1] ^= 1;
		TCT_EQ_INT(tc_xaead_open(back, key, nonce, ad, ad_len, bad, want_len),
		           TC_ERR_INVAL);
		nonce[0] ^= 1;
		TCT_EQ_INT(tc_xaead_open(back, key, nonce, ad, ad_len, want, want_len),
		           TC_ERR_INVAL);
		nonce[0] ^= 1;
		if (ad_len > 0) {
			ad[0] ^= 1;
			TCT_EQ_INT(
			    tc_xaead_open(back, key, nonce, ad, ad_len, want, want_len),
			    TC_ERR_INVAL);
			ad[0] ^= 1;
		}
	}
}

/* ---- WireGuard cookies -------------------------------------------------- */

static void test_cookies(void)
{
	TCT_CASE("cookie derivation matches wireguard-go");
	for (size_t i = 0; i < sizeof kCookieVectors / sizeof kCookieVectors[0];
	     i++) {
		uint8_t pk[32], secret[32], want_cookie[16], want_key[32];
		static uint8_t src[MAXBUF], msg[MAXBUF];
		uint8_t want_mac2[16];

		TCT_EQ_INT(unhex(pk, sizeof pk, kCookieVectors[i].responder_public),
		           32);
		TCT_EQ_INT(unhex(secret, sizeof secret, kCookieVectors[i].secret), 32);
		size_t src_len = unhex(src, MAXBUF, kCookieVectors[i].src);
		TCT_EQ_INT(unhex(want_cookie, sizeof want_cookie,
		                 kCookieVectors[i].cookie),
		           16);
		TCT_EQ_INT(unhex(want_key, sizeof want_key,
		                 kCookieVectors[i].cookie_key),
		           32);
		size_t msg_len = unhex(msg, MAXBUF, kCookieVectors[i].msg);
		TCT_EQ_INT(unhex(want_mac2, sizeof want_mac2, kCookieVectors[i].mac2),
		           16);

		uint8_t got[32];
		tc_wg_cookie_key(got, pk);
		if (memcmp(got, want_key, 32) != 0)
			TCT_FAILF("cookie key %s", kCookieVectors[i].name);
		tct_checks++;

		tc_wg_compute_cookie(got, secret, src, src_len);
		if (memcmp(got, want_cookie, 16) != 0)
			TCT_FAILF("cookie %s", kCookieVectors[i].name);
		tct_checks++;

		/* The vector's message already carries the mac2 wireguard-go
		 * computed, so writing ours over it must not change a byte. */
		static uint8_t copy[MAXBUF];
		memcpy(copy, msg, msg_len);
		tc_wg_add_mac2(copy, msg_len, want_cookie);
		if (memcmp(copy + msg_len - 16, want_mac2, 16) != 0)
			TCT_FAILF("mac2 %s", kCookieVectors[i].name);
		tct_checks++;

		TCT_TRUE(tc_wg_check_mac2(msg, msg_len, secret, src, src_len));

		/* And it must reject a message that was altered anywhere before
		 * mac2 -- including in mac1, which mac2 covers. */
		copy[0] ^= 1;
		TCT_TRUE(!tc_wg_check_mac2(copy, msg_len, secret, src, src_len));
		copy[0] ^= 1;
		copy[msg_len - 32] ^= 1; /* inside mac1 */
		TCT_TRUE(!tc_wg_check_mac2(copy, msg_len, secret, src, src_len));

		/* A different sender gets a different cookie, which is the entire
		 * point: a flood from a forged source cannot echo one back. */
		src[0] ^= 1;
		TCT_TRUE(!tc_wg_check_mac2(msg, msg_len, secret, src, src_len));
		src[0] ^= 1;
	}
}

static void test_cookie_reply(void)
{
	TCT_CASE("a cookie reply round-trips");
	uint8_t sk[32], pk[32], secret[32];
	TCT_EQ_INT(tc_x25519_keypair(sk, pk), TC_OK);
	TCT_EQ_INT(tc_random_bytes(secret, sizeof secret), TC_OK);

	static uint8_t msg[TC_WG_INITIATION_SIZE];
	TCT_EQ_INT(tc_random_bytes(msg, sizeof msg), TC_OK);
	msg[0] = TC_WG_MSG_INITIATION;
	const uint8_t *sent_mac1 = msg + sizeof msg - 32;
	const uint8_t src[32] = { 7 };

	uint8_t reply[TC_WG_COOKIE_REPLY_SIZE];
	TCT_EQ_INT(tc_wg_create_cookie_reply(reply, msg, sizeof msg, pk, secret,
	                                     src, sizeof src),
	           TC_OK);
	TCT_EQ_INT(reply[0], TC_WG_MSG_COOKIE_REPLY);
	/* The receiver index echoes the sender index being answered, so the
	 * initiator can tell which handshake it belongs to. */
	TCT_EQ_MEM(reply + 4, msg + 4, 4);

	uint8_t cookie[16];
	TCT_EQ_INT(tc_wg_consume_cookie_reply(cookie, reply, pk, sent_mac1),
	           TC_OK);

	TCT_CASE("the recovered cookie is the one the responder would check");
	uint8_t direct[16];
	tc_wg_compute_cookie(direct, secret, src, sizeof src);
	TCT_EQ_MEM(cookie, direct, 16);

	static uint8_t signed_msg[TC_WG_INITIATION_SIZE];
	memcpy(signed_msg, msg, sizeof msg);
	tc_wg_add_mac2(signed_msg, sizeof signed_msg, cookie);
	TCT_TRUE(tc_wg_check_mac2(signed_msg, sizeof signed_msg, secret, src,
	                          sizeof src));

	TCT_CASE("a reply from the wrong handshake does not open");
	/* The mac1 of the provoking message is the additional data, so a reply
	 * cannot be lifted out of one handshake and replayed into another. */
	uint8_t other_mac1[16];
	memcpy(other_mac1, sent_mac1, 16);
	other_mac1[0] ^= 1;
	TCT_EQ_INT(tc_wg_consume_cookie_reply(cookie, reply, pk, other_mac1),
	           TC_ERR_INVAL);

	TCT_CASE("a reply addressed to another peer does not open");
	uint8_t sk2[32], pk2[32];
	TCT_EQ_INT(tc_x25519_keypair(sk2, pk2), TC_OK);
	TCT_EQ_INT(tc_wg_consume_cookie_reply(cookie, reply, pk2, sent_mac1),
	           TC_ERR_INVAL);

	TCT_CASE("a corrupted reply does not open");
	reply[40] ^= 1;
	TCT_EQ_INT(tc_wg_consume_cookie_reply(cookie, reply, pk, sent_mac1),
	           TC_ERR_INVAL);
	reply[40] ^= 1;
	reply[0] = TC_WG_MSG_TRANSPORT;
	TCT_EQ_INT(tc_wg_consume_cookie_reply(cookie, reply, pk, sent_mac1),
	           TC_ERR_INVAL);

	TCT_CASE("two replies never reuse a nonce");
	/* The nonce is random rather than a counter, which is the reason this
	 * uses XChaCha at all: 96 bits would not be enough room to pick one
	 * safely. */
	uint8_t a[TC_WG_COOKIE_REPLY_SIZE], b[TC_WG_COOKIE_REPLY_SIZE];
	reply[0] = TC_WG_MSG_COOKIE_REPLY;
	TCT_EQ_INT(tc_wg_create_cookie_reply(a, msg, sizeof msg, pk, secret, src,
	                                     sizeof src),
	           TC_OK);
	TCT_EQ_INT(tc_wg_create_cookie_reply(b, msg, sizeof msg, pk, secret, src,
	                                     sizeof src),
	           TC_OK);
	TCT_TRUE(memcmp(a + 8, b + 8, 24) != 0);
}

static void test_cookie_exchange_against_go(void)
{
	TCT_CASE("a cookie exchange performed by wireguard-go round-trips here");
	/* The strongest of the cookie tests: their CookieChecker built the reply
	 * and their CookieGenerator consumed it and macked a second message. We
	 * have to recover the same cookie and arrive at the same mac2, with
	 * nothing transcribed from the specification. */
	for (size_t i = 0;
	     i < sizeof kCookieExchangeVectors / sizeof kCookieExchangeVectors[0];
	     i++) {
		uint8_t pk[32];
		static uint8_t msg1[MAXBUF], reply[MAXBUF], msg2[MAXBUF];
		TCT_EQ_INT(
		    unhex(pk, sizeof pk, kCookieExchangeVectors[i].responder_public),
		    32);
		size_t m1 = unhex(msg1, MAXBUF, kCookieExchangeVectors[i].msg1);
		size_t rl = unhex(reply, MAXBUF, kCookieExchangeVectors[i].reply);
		size_t m2 = unhex(msg2, MAXBUF, kCookieExchangeVectors[i].msg2);
		TCT_EQ_INT((int)rl, TC_WG_COOKIE_REPLY_SIZE);

		uint8_t cookie[TC_WG_COOKIE_LEN];
		if (tc_wg_consume_cookie_reply(cookie, reply, pk,
		                               msg1 + m1 - 2 * TC_WG_MAC_LEN) != TC_OK)
			TCT_FAILF("could not open %s", kCookieExchangeVectors[i].name);
		tct_checks++;

		/* Recompute mac2 over their second message and require it to match
		 * the one they wrote there. */
		uint8_t want[TC_WG_MAC_LEN];
		memcpy(want, msg2 + m2 - TC_WG_MAC_LEN, TC_WG_MAC_LEN);
		memset(msg2 + m2 - TC_WG_MAC_LEN, 0, TC_WG_MAC_LEN);
		tc_wg_add_mac2(msg2, m2, cookie);
		if (memcmp(msg2 + m2 - TC_WG_MAC_LEN, want, TC_WG_MAC_LEN) != 0)
			TCT_FAILF("mac2 disagrees for %s",
			          kCookieExchangeVectors[i].name);
		tct_checks++;
	}
}

int main(void)
{
	test_blake2s();
	test_hmac();
	test_kdf();
	test_x25519();
	test_aead();
	test_aead_counter();
	test_hsalsa20();
	test_secretbox();
	test_box();
	test_hchacha20();
	test_xaead();
	test_cookies();
	test_cookie_reply();
	test_cookie_exchange_against_go();
	test_random();
	return tct_report("crypto");
}
