/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Vectors come from tests/crypto_vectors.h, generated by tools/genvectors
 * from the same Go libraries WireGuard uses. Two of them (rfc7693-abc and
 * rfc7748-1) are the published RFC values, so the generator itself is
 * anchored to something external.
 */

#include "tc/crypto.h"
#include "tctest.h"

#include "crypto_vectors.h"

/* ---- hex helper ------------------------------------------------------ */

static int hexval(char c)
{
	if (c >= '0' && c <= '9')
		return c - '0';
	if (c >= 'a' && c <= 'f')
		return c - 'a' + 10;
	if (c >= 'A' && c <= 'F')
		return c - 'A' + 10;
	return -1;
}

/* unhex decodes a hex string into buf and returns its byte length, or
 * SIZE_MAX on malformed input or overflow. */
static size_t unhex(uint8_t *buf, size_t cap, const char *s)
{
	size_t n = strlen(s);
	if (n % 2 != 0 || n / 2 > cap)
		return (size_t)-1;
	for (size_t i = 0; i < n; i += 2) {
		int hi = hexval(s[i]), lo = hexval(s[i + 1]);
		if (hi < 0 || lo < 0)
			return (size_t)-1;
		buf[i / 2] = (uint8_t)(hi << 4 | lo);
	}
	return n / 2;
}

#define MAXBUF 2048
static uint8_t b_msg[MAXBUF], b_key[MAXBUF], b_want[MAXBUF];
static uint8_t b_a[MAXBUF], b_b[MAXBUF], b_c[MAXBUF], b_out[MAXBUF + 64];

/* ---- BLAKE2s --------------------------------------------------------- */

static void test_blake2s(void)
{
	for (size_t i = 0; i < sizeof kBlake2sVectors / sizeof kBlake2sVectors[0];
	     i++) {
		const char *name = kBlake2sVectors[i].name;
		TCT_CASE(name);

		size_t msg_len = unhex(b_msg, MAXBUF, kBlake2sVectors[i].msg);
		size_t key_len = unhex(b_key, MAXBUF, kBlake2sVectors[i].key);
		size_t want_len = unhex(b_want, MAXBUF, kBlake2sVectors[i].want);
		size_t outlen = (size_t)kBlake2sVectors[i].outlen;

		TCT_TRUE(msg_len != (size_t)-1 && key_len != (size_t)-1);
		TCT_EQ_INT(want_len, outlen);

		/* One-shot. */
		uint8_t got[TC_BLAKE2S_HASH_LEN];
		tc_blake2s(got, outlen, b_msg, msg_len,
		           key_len ? b_key : NULL, key_len);
		TCT_EQ_MEM(got, b_want, outlen);

		/* Incremental, one byte at a time. This is what catches a wrong
		 * final-block flag: the buffered block must not be compressed until
		 * we know no more data follows. */
		tc_blake2s_ctx ctx;
		tc_blake2s_init_key(&ctx, outlen, key_len ? b_key : NULL, key_len);
		for (size_t j = 0; j < msg_len; j++)
			tc_blake2s_update(&ctx, b_msg + j, 1);
		uint8_t got2[TC_BLAKE2S_HASH_LEN];
		tc_blake2s_final(&ctx, got2);
		TCT_EQ_MEM(got2, b_want, outlen);

		/* Incremental in awkward chunk sizes, straddling block boundaries. */
		const size_t chunks[] = { 1, 7, 63, 64, 65, 127, 128 };
		for (size_t ci = 0; ci < sizeof chunks / sizeof chunks[0]; ci++) {
			tc_blake2s_init_key(&ctx, outlen, key_len ? b_key : NULL, key_len);
			size_t off = 0;
			while (off < msg_len) {
				size_t take = chunks[ci];
				if (take > msg_len - off)
					take = msg_len - off;
				tc_blake2s_update(&ctx, b_msg + off, take);
				off += take;
			}
			uint8_t got3[TC_BLAKE2S_HASH_LEN];
			tc_blake2s_final(&ctx, got3);
			TCT_EQ_MEM(got3, b_want, outlen);
		}

		/* Zero-length updates must be no-ops. */
		tc_blake2s_init_key(&ctx, outlen, key_len ? b_key : NULL, key_len);
		tc_blake2s_update(&ctx, NULL, 0);
		tc_blake2s_update(&ctx, b_msg, msg_len);
		tc_blake2s_update(&ctx, NULL, 0);
		uint8_t got4[TC_BLAKE2S_HASH_LEN];
		tc_blake2s_final(&ctx, got4);
		TCT_EQ_MEM(got4, b_want, outlen);
	}

	TCT_CASE("final wipes the context");
	tc_blake2s_ctx ctx;
	uint8_t out[TC_BLAKE2S_HASH_LEN];
	tc_blake2s_init(&ctx, TC_BLAKE2S_HASH_LEN);
	tc_blake2s_update(&ctx, "secret", 6);
	tc_blake2s_final(&ctx, out);
	TCT_TRUE(tc_ct_is_zero(&ctx, sizeof ctx));
}

/* ---- HMAC-BLAKE2s ---------------------------------------------------- */

static void test_hmac(void)
{
	for (size_t i = 0;
	     i < sizeof kHmacBlake2sVectors / sizeof kHmacBlake2sVectors[0]; i++) {
		TCT_CASE(kHmacBlake2sVectors[i].name);

		size_t key_len = unhex(b_key, MAXBUF, kHmacBlake2sVectors[i].key);
		size_t in0_len = unhex(b_a, MAXBUF, kHmacBlake2sVectors[i].in0);
		size_t in1_len = unhex(b_b, MAXBUF, kHmacBlake2sVectors[i].in1);
		size_t want_len = unhex(b_want, MAXBUF, kHmacBlake2sVectors[i].want);
		TCT_EQ_INT(want_len, TC_BLAKE2S_HASH_LEN);

		uint8_t got[TC_BLAKE2S_HASH_LEN];
		tc_hmac_blake2s(got, key_len ? b_key : NULL, key_len,
		                in0_len ? b_a : NULL, in0_len,
		                in1_len ? b_b : NULL, in1_len);
		TCT_EQ_MEM(got, b_want, TC_BLAKE2S_HASH_LEN);
	}

	TCT_CASE("HMAC is not keyed BLAKE2s");
	/* These are different constructions. Confusing them would still produce
	 * plausible-looking output but would not interoperate, so assert they
	 * genuinely differ. */
	uint8_t key[32], msg[32], a[32], b[32];
	memset(key, 0xab, sizeof key);
	memset(msg, 0xcd, sizeof msg);
	tc_hmac_blake2s(a, key, sizeof key, msg, sizeof msg, NULL, 0);
	tc_blake2s(b, sizeof b, msg, sizeof msg, key, sizeof key);
	TCT_TRUE(memcmp(a, b, 32) != 0);
}

/* ---- WireGuard KDF --------------------------------------------------- */

static void test_kdf(void)
{
	for (size_t i = 0; i < sizeof kKdfVectors / sizeof kKdfVectors[0]; i++) {
		TCT_CASE(kKdfVectors[i].name);

		size_t key_len = unhex(b_key, MAXBUF, kKdfVectors[i].key);
		size_t in_len = unhex(b_msg, MAXBUF, kKdfVectors[i].input);
		TCT_EQ_INT(key_len, TC_BLAKE2S_HASH_LEN);

		uint8_t t0[32], t1[32], t2[32];
		size_t w0 = unhex(b_a, MAXBUF, kKdfVectors[i].t0);
		size_t w1 = unhex(b_b, MAXBUF, kKdfVectors[i].t1);
		size_t w2 = unhex(b_c, MAXBUF, kKdfVectors[i].t2);
		(void)w1;
		(void)w2;
		TCT_EQ_INT(w0, 32);

		switch (kKdfVectors[i].n) {
		case 1:
			tc_kdf1(t0, b_key, in_len ? b_msg : NULL, in_len);
			TCT_EQ_MEM(t0, b_a, 32);
			break;
		case 2:
			tc_kdf2(t0, t1, b_key, in_len ? b_msg : NULL, in_len);
			TCT_EQ_MEM(t0, b_a, 32);
			TCT_EQ_MEM(t1, b_b, 32);
			break;
		case 3:
			tc_kdf3(t0, t1, t2, b_key, in_len ? b_msg : NULL, in_len);
			TCT_EQ_MEM(t0, b_a, 32);
			TCT_EQ_MEM(t1, b_b, 32);
			TCT_EQ_MEM(t2, b_c, 32);
			break;
		default:
			TCT_FAILF("unexpected KDF arity %d", kKdfVectors[i].n);
			break;
		}
	}

	TCT_CASE("KDF outputs are distinct");
	uint8_t key[32], t0[32], t1[32], t2[32];
	memset(key, 0x11, sizeof key);
	tc_kdf3(t0, t1, t2, key, "x", 1);
	TCT_TRUE(memcmp(t0, t1, 32) != 0);
	TCT_TRUE(memcmp(t1, t2, 32) != 0);
	TCT_TRUE(memcmp(t0, t2, 32) != 0);

	TCT_CASE("KDF1 agrees with KDF2's first output");
	uint8_t a0[32], b0[32], b1[32];
	tc_kdf1(a0, key, "abc", 3);
	tc_kdf2(b0, b1, key, "abc", 3);
	TCT_EQ_MEM(a0, b0, 32);
}

/* ---- X25519 ---------------------------------------------------------- */

static void test_x25519(void)
{
	for (size_t i = 0; i < sizeof kX25519Vectors / sizeof kX25519Vectors[0];
	     i++) {
		TCT_CASE(kX25519Vectors[i].name);

		uint8_t sk[32], pk[32], want[32], got[32];
		TCT_EQ_INT(unhex(sk, sizeof sk, kX25519Vectors[i].scalar), 32);
		TCT_EQ_INT(unhex(pk, sizeof pk, kX25519Vectors[i].point), 32);

		size_t want_len = unhex(want, sizeof want, kX25519Vectors[i].want);
		int rc = tc_x25519(got, sk, pk);

		if (want_len == 0) {
			/* Go reported a low-order point; we must reject it too. */
			TCT_EQ_INT(rc, TC_ERR_INVAL);
		} else {
			TCT_EQ_INT(rc, TC_OK);
			TCT_EQ_MEM(got, want, 32);
		}
	}

	for (size_t i = 0;
	     i < sizeof kX25519BaseVectors / sizeof kX25519BaseVectors[0]; i++) {
		TCT_CASE(kX25519BaseVectors[i].name);
		uint8_t sk[32], want[32], got[32];
		TCT_EQ_INT(unhex(sk, sizeof sk, kX25519BaseVectors[i].sk), 32);
		TCT_EQ_INT(unhex(want, sizeof want, kX25519BaseVectors[i].pk), 32);
		TCT_EQ_INT(tc_x25519_base(got, sk), TC_OK);
		TCT_EQ_MEM(got, want, 32);
	}

	TCT_CASE("small-order public keys are rejected");
	for (size_t i = 0;
	     i < sizeof kX25519LowOrder / sizeof kX25519LowOrder[0]; i++) {
		uint8_t sk[32], pk[32], got[32];
		memset(sk, 0x77, sizeof sk);
		tc_x25519_clamp(sk);
		TCT_EQ_INT(unhex(pk, sizeof pk, kX25519LowOrder[i]), 32);
		TCT_EQ_INT(tc_x25519(got, sk, pk), TC_ERR_INVAL);
		/* And nothing usable is left behind. */
		TCT_TRUE(tc_ct_is_zero(got, sizeof got));
	}

	TCT_CASE("clamping matches WireGuard");
	uint8_t sk[32];
	memset(sk, 0xff, sizeof sk);
	tc_x25519_clamp(sk);
	TCT_EQ_INT(sk[0] & 7, 0);        /* low three bits cleared */
	TCT_EQ_INT(sk[31] & 0x80, 0);    /* top bit cleared */
	TCT_EQ_INT(sk[31] & 0x40, 0x40); /* second-highest bit set */

	TCT_CASE("a generated keypair agrees with itself");
	uint8_t pk[32], pk2[32];
	TCT_EQ_INT(tc_x25519_keypair(sk, pk), TC_OK);
	TCT_EQ_INT(tc_x25519_base(pk2, sk), TC_OK);
	TCT_EQ_MEM(pk, pk2, 32);

	TCT_CASE("Diffie-Hellman agrees in both directions");
	uint8_t ska[32], pka[32], skb[32], pkb[32], ss1[32], ss2[32];
	TCT_EQ_INT(tc_x25519_keypair(ska, pka), TC_OK);
	TCT_EQ_INT(tc_x25519_keypair(skb, pkb), TC_OK);
	TCT_EQ_INT(tc_x25519(ss1, ska, pkb), TC_OK);
	TCT_EQ_INT(tc_x25519(ss2, skb, pka), TC_OK);
	TCT_EQ_MEM(ss1, ss2, 32);
}

/* ---- ChaCha20-Poly1305 ----------------------------------------------- */

static void test_aead(void)
{
	for (size_t i = 0; i < sizeof kAeadVectors / sizeof kAeadVectors[0]; i++) {
		TCT_CASE(kAeadVectors[i].name);

		uint8_t key[32], nonce[12];
		TCT_EQ_INT(unhex(key, sizeof key, kAeadVectors[i].key), 32);
		TCT_EQ_INT(unhex(nonce, sizeof nonce, kAeadVectors[i].nonce), 12);
		size_t ad_len = unhex(b_a, MAXBUF, kAeadVectors[i].ad);
		size_t pt_len = unhex(b_msg, MAXBUF, kAeadVectors[i].pt);
		size_t ct_len = unhex(b_want, MAXBUF, kAeadVectors[i].ct);
		TCT_EQ_INT(ct_len, pt_len + TC_AEAD_TAG_LEN);

		TCT_EQ_INT(tc_aead_seal_nonce(b_out, key, nonce, ad_len ? b_a : NULL,
		                              ad_len, pt_len ? b_msg : NULL, pt_len),
		           TC_OK);
		TCT_EQ_MEM(b_out, b_want, ct_len);

		/* Decrypting the Go-produced ciphertext must give the plaintext. */
		TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce, ad_len ? b_a : NULL,
		                              ad_len, b_want, ct_len),
		           TC_OK);
		if (pt_len != 0)
			TCT_EQ_MEM(b_b, b_msg, pt_len);

		/* Flipping any one bit of the tag, ciphertext or AD must fail. */
		if (ct_len > 0) {
			memcpy(b_c, b_want, ct_len);
			b_c[ct_len - 1] ^= 1; /* tag */
			TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce,
			                              ad_len ? b_a : NULL, ad_len, b_c,
			                              ct_len),
			           TC_ERR_INVAL);
		}
		if (pt_len > 0) {
			memcpy(b_c, b_want, ct_len);
			b_c[0] ^= 1; /* ciphertext */
			TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce,
			                              ad_len ? b_a : NULL, ad_len, b_c,
			                              ct_len),
			           TC_ERR_INVAL);
		}
		if (ad_len > 0) {
			b_a[0] ^= 1;
			TCT_EQ_INT(tc_aead_open_nonce(b_b, key, nonce, b_a, ad_len,
			                              b_want, ct_len),
			           TC_ERR_INVAL);
			b_a[0] ^= 1;
		}
	}
}

static void test_aead_counter(void)
{
	for (size_t i = 0;
	     i < sizeof kAeadCounterVectors / sizeof kAeadCounterVectors[0]; i++) {
		TCT_CASE(kAeadCounterVectors[i].name);

		uint8_t key[32];
		TCT_EQ_INT(unhex(key, sizeof key, kAeadCounterVectors[i].key), 32);
		size_t ad_len = unhex(b_a, MAXBUF, kAeadCounterVectors[i].ad);
		size_t pt_len = unhex(b_msg, MAXBUF, kAeadCounterVectors[i].pt);
		size_t ct_len = unhex(b_want, MAXBUF, kAeadCounterVectors[i].ct);

		uint64_t ctr = (uint64_t)kAeadCounterVectors[i].counter;

		TCT_EQ_INT(tc_aead_seal(b_out, key, ctr, b_a, ad_len, b_msg, pt_len),
		           TC_OK);
		TCT_EQ_MEM(b_out, b_want, ct_len);

		TCT_EQ_INT(tc_aead_open(b_b, key, ctr, b_a, ad_len, b_want, ct_len),
		           TC_OK);
		TCT_EQ_MEM(b_b, b_msg, pt_len);

		/* A different counter must not authenticate. */
		TCT_EQ_INT(tc_aead_open(b_b, key, ctr ^ 1u, b_a, ad_len, b_want,
		                        ct_len),
		           TC_ERR_INVAL);
	}

	TCT_CASE("open rejects input shorter than the tag");
	uint8_t key[32] = { 0 }, tiny[8] = { 0 };
	TCT_EQ_INT(tc_aead_open(b_b, key, 0, NULL, 0, tiny, sizeof tiny),
	           TC_ERR_INVAL);

	TCT_CASE("in-place encryption works");
	uint8_t k2[32];
	memset(k2, 0x5a, sizeof k2);
	uint8_t inplace[32 + TC_AEAD_TAG_LEN];
	memset(inplace, 0x11, 32);
	uint8_t expect[32 + TC_AEAD_TAG_LEN];
	TCT_EQ_INT(tc_aead_seal(expect, k2, 7, NULL, 0, inplace, 32), TC_OK);
	TCT_EQ_INT(tc_aead_seal(inplace, k2, 7, NULL, 0, inplace, 32), TC_OK);
	TCT_EQ_MEM(inplace, expect, sizeof expect);
}

/* ---- CSPRNG ---------------------------------------------------------- */

static void test_random(void)
{
	TCT_CASE("random init succeeds");
	TCT_EQ_INT(tc_random_init(), TC_OK);

	TCT_CASE("random bytes are not constant");
	uint8_t a[64], b[64];
	TCT_EQ_INT(tc_random_bytes(a, sizeof a), TC_OK);
	TCT_EQ_INT(tc_random_bytes(b, sizeof b), TC_OK);
	TCT_TRUE(memcmp(a, b, sizeof a) != 0);
	TCT_TRUE(!tc_ct_is_zero(a, sizeof a));

	TCT_CASE("zero-length request is fine");
	TCT_EQ_INT(tc_random_bytes(a, 0), TC_OK);

	TCT_CASE("a large request is filled");
	static uint8_t big[70000]; /* larger than MBEDTLS_CTR_DRBG_MAX_REQUEST */
	TCT_EQ_INT(tc_random_bytes(big, sizeof big), TC_OK);
	/* The tail must have been written, not left zero by a short read. */
	TCT_TRUE(!tc_ct_is_zero(big + sizeof big - 64, 64));

	TCT_CASE("null buffer is rejected");
	TCT_EQ_INT(tc_random_bytes(NULL, 8), TC_ERR_INVAL);
}

int main(void)
{
	test_blake2s();
	test_hmac();
	test_kdf();
	test_x25519();
	test_aead();
	test_aead_counter();
	test_random();
	return tct_report("crypto");
}
