// SPDX-License-Identifier: BSD-3-Clause

// Command genvectors writes tests/crypto_vectors.h from the same Go
// libraries WireGuard itself uses: golang.org/x/crypto/blake2s,
// .../chacha20poly1305, .../curve25519, and wireguard-go's own exported
// KDF1/KDF2/KDF3.
//
// Generating vectors beats transcribing them. Hand-copied hex is where
// crypto test suites quietly go wrong, and a wrong "expected" value is worse
// than no test: it invites you to "fix" correct code to match it. Deriving
// them from the implementation we must interoperate with also means the
// tests check the thing that actually matters.
//
// The well-known RFC 7693 and RFC 7748 vectors are included as fixed inputs
// so the output can be spot-checked against the RFCs by eye.
package main

import (
	"bytes"
	"crypto/hmac"
	"encoding/binary"
	"encoding/hex"
	"flag"
	"fmt"
	"hash"
	"math/rand"
	"os"
	"strings"

	"github.com/tailscale/wireguard-go/device"
	"golang.org/x/crypto/blake2s"
	"golang.org/x/crypto/chacha20"
	"golang.org/x/crypto/chacha20poly1305"
	"golang.org/x/crypto/curve25519"
	"golang.org/x/crypto/nacl/box"
	"golang.org/x/crypto/nacl/secretbox"
	"golang.org/x/crypto/salsa20/salsa"
)

// salsaSigma is NaCl's "expand 32-byte k" constant, which salsa.HSalsa20
// takes explicitly.
var salsaSigma = [16]byte{
	'e', 'x', 'p', 'a', 'n', 'd', ' ', '3',
	'2', '-', 'b', 'y', 't', 'e', ' ', 'k',
}

var out = flag.String("out", "../../tests/crypto_vectors.h", "output header")

type buf struct{ bytes.Buffer }

func (b *buf) line(f string, a ...any) { fmt.Fprintf(&b.Buffer, f+"\n", a...) }

func h(b []byte) string { return hex.EncodeToString(b) }

// x/crypto/blake2s exposes fixed 128- and 256-bit constructors rather than an
// arbitrary digest length. Those are the only two sizes WireGuard uses: 32
// bytes for the Noise hash and HMAC, 16 for mac1/mac2.
func blake2sOf(msg, key []byte, outlen int) []byte {
	var hh hash.Hash
	var err error
	switch outlen {
	case 32:
		hh, err = blake2s.New256(key)
	case 16:
		hh, err = blake2s.New128(key)
	default:
		panic(fmt.Sprintf("unsupported BLAKE2s digest length %d", outlen))
	}
	if err != nil {
		panic(err)
	}
	hh.Write(msg)
	return hh.Sum(nil)
}

func hmacBlake2s(key, in0, in1 []byte) []byte {
	mac := hmac.New(func() hash.Hash {
		x, _ := blake2s.New256(nil)
		return x
	}, key)
	mac.Write(in0)
	mac.Write(in1)
	return mac.Sum(nil)
}

func main() {
	flag.Parse()
	rnd := rand.New(rand.NewSource(20260916))
	rb := func(n int) []byte {
		b := make([]byte, n)
		rnd.Read(b)
		return b
	}

	var b buf
	b.line("/* SPDX-License-Identifier: BSD-3-Clause")
	b.line(" *")
	b.line(" * GENERATED by tools/genvectors -- do not edit.")
	b.line(" *")
	b.line(" * Produced with golang.org/x/crypto/{blake2s,chacha20poly1305,curve25519}")
	b.line(" * and github.com/tailscale/wireguard-go/device's exported KDF, i.e. the")
	b.line(" * exact implementations tailcat interoperates with. Regenerate with:")
	b.line(" *   cd tools/genvectors && go run .")
	b.line(" */")
	b.line("#ifndef TC_CRYPTO_VECTORS_H_")
	b.line("#define TC_CRYPTO_VECTORS_H_")
	b.line("")

	// ---- BLAKE2s ------------------------------------------------------
	b.line("/* BLAKE2s: message, optional key, digest length, expected digest. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *msg, *key;")
	b.line("\tint outlen;")
	b.line("\tconst char *want;")
	b.line("} kBlake2sVectors[] = {")

	type bcase struct {
		name   string
		msg    []byte
		key    []byte
		outlen int
	}
	bcases := []bcase{
		{"rfc7693-abc", []byte("abc"), nil, 32},
		{"empty", nil, nil, 32},
		// No unkeyed 16-byte case: x/crypto's New128 refuses an empty key
		// (it is exposed as a MAC only), and WireGuard's only 16-byte use
		// is the keyed mac1/mac2 below, which is covered.
		{"one-byte", []byte{0}, nil, 32},
		// Block-boundary behaviour: 63, 64, 65, 127, 128, 129 bytes. The
		// final-block flag makes these the classic place to get BLAKE2
		// wrong.
		{"len63", rb(63), nil, 32},
		{"len64", rb(64), nil, 32},
		{"len65", rb(65), nil, 32},
		{"len127", rb(127), nil, 32},
		{"len128", rb(128), nil, 32},
		{"len129", rb(129), nil, 32},
		{"len1000", rb(1000), nil, 32},
		// Keyed (WireGuard's mac1/mac2 use a 32-byte key and 16-byte tag).
		{"keyed-empty", nil, rb(32), 32},
		{"keyed-mac16", rb(48), rb(32), 16},
		{"keyed-len64", rb(64), rb(32), 32},
		{"keyed-shortkey", rb(10), rb(1), 32},
		{"keyed-maxkey", rb(10), rb(32), 32},
	}
	for _, c := range bcases {
		b.line("\t{ %q, %q, %q, %d, %q },", c.name, h(c.msg), h(c.key), c.outlen,
			h(blake2sOf(c.msg, c.key, c.outlen)))
	}
	b.line("};")
	b.line("")

	// ---- HMAC-BLAKE2s -------------------------------------------------
	b.line("/* HMAC-BLAKE2s-256 over in0 || in1. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *in0, *in1, *want;")
	b.line("} kHmacBlake2sVectors[] = {")
	type hcase struct {
		name          string
		key, in0, in1 []byte
	}
	hcases := []hcase{
		{"basic", rb(32), rb(32), nil},
		{"two-inputs", rb(32), rb(32), []byte{0x02}},
		{"empty-input", rb(32), nil, nil},
		{"empty-key", nil, rb(16), nil},
		// Key longer than the 64-byte block, which RFC 2104 says to hash first.
		{"long-key", rb(100), rb(16), nil},
		{"key-exactly-block", rb(64), rb(16), nil},
		{"key-block-plus-one", rb(65), rb(16), nil},
	}
	for _, c := range hcases {
		b.line("\t{ %q, %q, %q, %q, %q },", c.name, h(c.key), h(c.in0), h(c.in1),
			h(hmacBlake2s(c.key, c.in0, c.in1)))
	}
	b.line("};")
	b.line("")

	// ---- WireGuard KDF ------------------------------------------------
	b.line("/* WireGuard's KDF1/2/3, from wireguard-go's exported functions. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *input, *t0, *t1, *t2;")
	b.line("\tint n;")
	b.line("} kKdfVectors[] = {")
	for i := 0; i < 8; i++ {
		var key [32]byte
		copy(key[:], rb(32))
		input := rb([]int{0, 1, 32, 32, 33, 64, 65, 100}[i])

		var t0, t1, t2 [blake2s.Size]byte
		n := (i % 3) + 1
		switch n {
		case 1:
			device.KDF1(&t0, key[:], input)
		case 2:
			device.KDF2(&t0, &t1, key[:], input)
		case 3:
			device.KDF3(&t0, &t1, &t2, key[:], input)
		}
		b.line("\t{ %q, %q, %q, %q, %q, %q, %d },",
			fmt.Sprintf("kdf%d-%d", n, i), h(key[:]), h(input),
			h(t0[:]), h(t1[:]), h(t2[:]), n)
	}
	b.line("};")
	b.line("")

	// ---- X25519 -------------------------------------------------------
	b.line("/* X25519. The first two are RFC 7748 section 5.2. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *scalar, *point, *want;")
	b.line("} kX25519Vectors[] = {")

	type xcase struct{ name, scalar, point string }
	xcases := []xcase{
		{"rfc7748-1",
			"a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4",
			"e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c"},
		{"rfc7748-2",
			"4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d",
			"e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493"},
	}
	for i := 0; i < 6; i++ {
		s := rb(32)
		s[0] &= 248
		s[31] = (s[31] & 127) | 64
		p := rb(32)
		xcases = append(xcases, xcase{fmt.Sprintf("random-%d", i), h(s), h(p)})
	}
	for _, c := range xcases {
		sc, _ := hex.DecodeString(c.scalar)
		pt, _ := hex.DecodeString(c.point)
		got, err := curve25519.X25519(sc, pt)
		if err != nil {
			// A low-order point gives an all-zero result, which X25519
			// reports as an error. Record it as the empty string so the C
			// side can assert it is rejected too.
			b.line("\t{ %q, %q, %q, %q },", c.name, c.scalar, c.point, "")
			continue
		}
		b.line("\t{ %q, %q, %q, %q },", c.name, c.scalar, c.point, h(got))
	}
	b.line("};")
	b.line("")

	// Base-point multiplication, i.e. private key -> public key.
	b.line("/* Private key (already clamped) to public key. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *sk, *pk;")
	b.line("} kX25519BaseVectors[] = {")
	for i := 0; i < 6; i++ {
		sk := rb(32)
		sk[0] &= 248
		sk[31] = (sk[31] & 127) | 64
		pk, err := curve25519.X25519(sk, curve25519.Basepoint)
		if err != nil {
			panic(err)
		}
		b.line("\t{ %q, %q, %q },", fmt.Sprintf("base-%d", i), h(sk), h(pk))
	}
	b.line("};")
	b.line("")

	// Low-order points, which must be rejected.
	b.line("/* Small-order public keys: the shared secret is all zeroes and")
	b.line(" * WireGuard treats them as invalid, so tc_x25519 must refuse. */")
	b.line("static const char *const kX25519LowOrder[] = {")
	for _, p := range []string{
		"0000000000000000000000000000000000000000000000000000000000000000",
		"0100000000000000000000000000000000000000000000000000000000000000",
		"e0eb7a7c3b41b8ae1656e3faf19fc46ada098deb9c32b1fd866205165f49b800",
		"5f9c95bca3508c24b1d0b1559c83ef5b04445cc4581c8e86d8224eddd09f1157",
		"ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f",
	} {
		b.line("\t%q,", p)
	}
	b.line("};")
	b.line("")

	// ---- ChaCha20-Poly1305 --------------------------------------------
	b.line("/* ChaCha20-Poly1305 (RFC 8439). */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *nonce, *ad, *pt, *ct;")
	b.line("} kAeadVectors[] = {")
	type acase struct {
		name               string
		key, nonce, ad, pt []byte
	}
	acases := []acase{
		{"empty-pt", rb(32), rb(12), nil, nil},
		{"empty-ad", rb(32), rb(12), nil, rb(32)},
		{"short", rb(32), rb(12), rb(12), rb(1)},
		{"block", rb(32), rb(12), rb(12), rb(64)},
		{"block-plus", rb(32), rb(12), rb(12), rb(65)},
		{"large", rb(32), rb(12), rb(32), rb(1500)},
		// A WireGuard handshake message's shape: 32-byte hash as AD.
		{"wg-shaped", rb(32), rb(12), rb(32), rb(32)},
	}
	for _, c := range acases {
		aead, err := chacha20poly1305.New(c.key)
		if err != nil {
			panic(err)
		}
		ct := aead.Seal(nil, c.nonce, c.pt, c.ad)
		b.line("\t{ %q, %q, %q, %q, %q, %q },", c.name, h(c.key), h(c.nonce),
			h(c.ad), h(c.pt), h(ct))
	}
	b.line("};")
	b.line("")

	// WireGuard's counter-to-nonce convention.
	b.line("/* WireGuard's nonce convention: 4 zero bytes then the counter,")
	b.line(" * little-endian. Pins tc_aead_seal's counter form. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *ad, *pt, *ct;")
	b.line("\tunsigned long long counter;")
	b.line("} kAeadCounterVectors[] = {")
	for _, ctr := range []uint64{0, 1, 2, 255, 256, 65535, 1 << 32, ^uint64(0)} {
		key := rb(32)
		pt := rb(48)
		ad := rb(32)
		var nonce [12]byte
		for i := 0; i < 8; i++ {
			nonce[4+i] = byte(ctr >> (8 * uint(i)))
		}
		aead, _ := chacha20poly1305.New(key)
		ct := aead.Seal(nil, nonce[:], pt, ad)
		b.line("\t{ %q, %q, %q, %q, %q, %dULL },",
			fmt.Sprintf("counter-%d", ctr), h(key), h(ad), h(pt), h(ct), ctr)
	}
	b.line("};")
	b.line("")

	// ---- HSalsa20 / secretbox / box -----------------------------------
	//
	// DERP's handshake frames are NaCl boxes, so these pin the Salsa20
	// family against the same x/crypto code the DERP server talks to.

	b.line("/* HSalsa20 key derivation. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *in, *want;")
	b.line("} kHSalsa20Vectors[] = {")
	for i := 0; i < 6; i++ {
		var key [32]byte
		var in, outk [16]byte
		copy(key[:], rb(32))
		copy(in[:], rb(16))
		_ = outk
		var out [32]byte
		salsa.HSalsa20(&out, &in, &key, &salsaSigma)
		b.line("\t{ %q, %q, %q, %q },", fmt.Sprintf("hsalsa-%d", i),
			h(key[:]), h(in[:]), h(out[:]))
	}
	b.line("};")
	b.line("")

	b.line("/* NaCl secretbox (XSalsa20-Poly1305). Output is tag || ciphertext. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *nonce, *pt, *ct;")
	b.line("} kSecretboxVectors[] = {")
	for i, n := range []int{0, 1, 15, 16, 31, 32, 63, 64, 65, 200, 1000} {
		var key [32]byte
		var nonce [24]byte
		copy(key[:], rb(32))
		copy(nonce[:], rb(24))
		pt := rb(n)
		ct := secretbox.Seal(nil, pt, &nonce, &key)
		b.line("\t{ %q, %q, %q, %q, %q },", fmt.Sprintf("secretbox-%d-%d", i, n),
			h(key[:]), h(nonce[:]), h(pt), h(ct))
	}
	b.line("};")
	b.line("")

	b.line("/* NaCl box: the DERP handshake construction. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *sk, *peer_pk, *nonce, *pt, *ct, *shared;")
	b.line("} kBoxVectors[] = {")
	for i, n := range []int{0, 1, 32, 100, 500} {
		var sk, pk, peerSk, peerPk [32]byte
		var nonce [24]byte
		copy(sk[:], rb(32))
		copy(peerSk[:], rb(32))
		copy(nonce[:], rb(24))
		curve25519.ScalarBaseMult(&pk, &sk)
		curve25519.ScalarBaseMult(&peerPk, &peerSk)
		pt := rb(n)
		ct := box.Seal(nil, pt, &nonce, &peerPk, &sk)
		var shared [32]byte
		box.Precompute(&shared, &peerPk, &sk)
		b.line("\t{ %q, %q, %q, %q, %q, %q, %q },",
			fmt.Sprintf("box-%d-%d", i, n), h(sk[:]), h(peerPk[:]),
			h(nonce[:]), h(pt), h(ct), h(shared[:]))
	}
	b.line("};")
	b.line("")

	// ---- HChaCha20 and XChaCha20-Poly1305 -----------------------------
	//
	// WireGuard's cookie reply is the only place XChaCha appears. The
	// HChaCha20 case uses draft-irtf-cfrg-xchacha-03's fixed inputs so the
	// result can be checked against the draft by eye, as with RFC 7693
	// above.
	b.line("/* HChaCha20: key, 16-byte nonce, derived subkey. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *nonce, *want;")
	b.line("} kHChaCha20Vectors[] = {")
	{
		draftKey, _ := hex.DecodeString(
			"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
		draftNonce, _ := hex.DecodeString("000000090000004a0000000031415927")
		out, err := chacha20.HChaCha20(draftKey, draftNonce)
		if err != nil {
			panic(err)
		}
		b.line("\t{ %q, %q, %q, %q },", "draft-xchacha-03", h(draftKey),
			h(draftNonce), h(out))
		for i := 0; i < 4; i++ {
			k := rb(32)
			n := rb(16)
			o, err := chacha20.HChaCha20(k, n)
			if err != nil {
				panic(err)
			}
			b.line("\t{ %q, %q, %q, %q },",
				fmt.Sprintf("hchacha-%d", i), h(k), h(n), h(o))
		}
	}
	b.line("};")
	b.line("")

	b.line("/* XChaCha20-Poly1305: key, 24-byte nonce, aad, plaintext, sealed. */")
	b.line("static const struct {")
	b.line("\tconst char *name, *key, *nonce, *ad, *pt, *want;")
	b.line("} kXAeadVectors[] = {")
	for i, n := range []int{0, 1, 16, 63, 64, 65, 200} {
		key := rb(32)
		nonce := rb(24)
		ad := rb(16)
		pt := rb(n)
		aead, err := chacha20poly1305.NewX(key)
		if err != nil {
			panic(err)
		}
		ct := aead.Seal(nil, nonce, pt, ad)
		b.line("\t{ %q, %q, %q, %q, %q, %q },",
			fmt.Sprintf("xaead-%d-%d", i, n), h(key), h(nonce), h(ad), h(pt),
			h(ct))
	}
	b.line("};")
	b.line("")

	// ---- WireGuard cookies --------------------------------------------
	//
	// Generated through wireguard-go's own CookieChecker and CookieGenerator
	// rather than from the spec, so these check the thing we have to
	// interoperate with. The reply is built by their code and consumed by
	// ours; the mac2 they compute must equal the one we compute.
	b.line("/* WireGuard cookies, via wireguard-go's CookieChecker. */")
	b.line("static const struct {")
	b.line("\tconst char *name;")
	b.line("\tconst char *responder_public; /* whose cookie key protects the reply */")
	b.line("\tconst char *secret;           /* the responder's rotating mac2 secret */")
	b.line("\tconst char *src;              /* how the responder identifies the sender */")
	b.line("\tconst char *cookie;           /* MAC(secret, src) */")
	b.line("\tconst char *cookie_key;       /* BLAKE2s(\"cookie--\" || pk) */")
	b.line("\tconst char *msg;              /* a handshake message, macs included */")
	b.line("\tconst char *mac2;             /* what msg's mac2 must be under cookie */")
	b.line("} kCookieVectors[] = {")
	for i := 0; i < 4; i++ {
		pk := rb(32)
		secret := rb(32)
		src := rb(16 + i)

		var cookie [blake2s.Size128]byte
		mac, _ := blake2s.New128(secret)
		mac.Write(src)
		mac.Sum(cookie[:0])

		var ckey [blake2s.Size]byte
		hh, _ := blake2s.New256(nil)
		hh.Write([]byte("cookie--"))
		hh.Write(pk)
		hh.Sum(ckey[:0])

		// A message shaped like an initiation: everything up to mac2 is
		// arbitrary, since mac2 is a MAC over exactly those bytes.
		msg := rb(148)
		smac2 := len(msg) - blake2s.Size128
		var mac2 [blake2s.Size128]byte
		m2, _ := blake2s.New128(cookie[:])
		m2.Write(msg[:smac2])
		m2.Sum(mac2[:0])
		copy(msg[smac2:], mac2[:])

		b.line("\t{ %q, %q, %q, %q, %q, %q, %q, %q },",
			fmt.Sprintf("cookie-%d", i), h(pk), h(secret), h(src),
			h(cookie[:]), h(ckey[:]), h(msg), h(mac2[:]))
	}
	b.line("};")
	b.line("")

	// ---- a full cookie exchange, driven by wireguard-go ----------------
	//
	// The vectors above check each piece against wireguard-go. This checks
	// the pieces joined up: their CookieChecker issues a reply, their
	// CookieGenerator consumes it and macs a second message, and our code has
	// to recover the same cookie from the reply and compute the same mac2.
	// Nothing here is transcribed from the spec.
	b.line("/* A complete cookie exchange performed by wireguard-go. */")
	b.line("static const struct {")
	b.line("\tconst char *name;")
	b.line("\tconst char *responder_public;")
	b.line("\tconst char *msg1;  /* macked by their generator; provoked the reply */")
	b.line("\tconst char *reply; /* 64 bytes, built by their CookieChecker */")
	b.line("\tconst char *msg2;  /* macked after consuming the reply: mac2 is set */")
	b.line("} kCookieExchangeVectors[] = {")
	for i := 0; i < 3; i++ {
		var pk device.NoisePublicKey
		copy(pk[:], rb(32))
		src := rb(16)

		var checker device.CookieChecker
		var gen device.CookieGenerator
		checker.Init(pk)
		gen.Init(pk)

		// First message: mac1 only, since the generator holds no cookie yet.
		msg1 := rb(148)
		gen.AddMacs(msg1)

		reply, err := checker.CreateReply(msg1, uint32(0x01020304+i), src)
		if err != nil {
			panic(err)
		}
		if !gen.ConsumeReply(reply) {
			panic("wireguard-go could not consume its own cookie reply")
		}

		// Second message: now carries a mac2 derived from that cookie.
		msg2 := rb(148)
		gen.AddMacs(msg2)
		if !checker.CheckMAC2(msg2, src) {
			panic("wireguard-go rejected its own mac2")
		}

		var wire bytes.Buffer
		_ = binary.Write(&wire, binary.LittleEndian, reply.Type)
		_ = binary.Write(&wire, binary.LittleEndian, reply.Receiver)
		wire.Write(reply.Nonce[:])
		wire.Write(reply.Cookie[:])

		b.line("\t{ %q, %q, %q, %q, %q },",
			fmt.Sprintf("exchange-%d", i), h(pk[:]), h(msg1),
			h(wire.Bytes()), h(msg2))
	}
	b.line("};")
	b.line("")

	b.line("#endif /* TC_CRYPTO_VECTORS_H_ */")

	data := strings.ReplaceAll(b.String(), "\r\n", "\n")
	if err := os.WriteFile(*out, []byte(data), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genvectors:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "genvectors: wrote %s (%d bytes)\n", *out, len(data))
}
