// SPDX-License-Identifier: BSD-3-Clause

// Command genssh writes tests/ssh_vectors.h from golang.org/x/crypto/ssh and
// the standard library, which is the same choice genvectors makes and for the
// same reason: a hand-transcribed expected value is worse than no test,
// because it invites you to "fix" correct code to match it.
//
// What is anchored here is the wire encoding of RFC 4251 section 5 -- string,
// mpint and name-list -- plus the ssh-ed25519 public key and signature blobs.
// Those are the encodings that everything above them is hashed over, so a
// disagreement in any of them shows up as an exchange-hash mismatch and
// nothing more specific. They are worth pinning against the implementation we
// have to interoperate with rather than against a reading of the RFC.
//
// x/crypto/ssh keeps its marshalling helpers unexported, so the encodings are
// reached through the exported surfaces that use them: ssh.Marshal for
// structs, and ssh.NewPublicKey / Signer.Sign for the key blobs.
package main

import (
	"crypto/ed25519"
	"encoding/hex"
	"flag"
	"fmt"
	"math/big"
	"math/rand"
	"os"
	"strings"

	"golang.org/x/crypto/ssh"
)

func hexs(b []byte) string { return hex.EncodeToString(b) }

// emit writes one vector as a C string pair.
func emit(sb *strings.Builder, name, in, want string) {
	fmt.Fprintf(sb, "\t{ \"%s\", \"%s\", \"%s\" },\n", name, in, want)
}

// --- string -----------------------------------------------------------

// stringOf returns ssh.Marshal's encoding of a single []byte field, which is
// exactly the RFC 4251 "string" type: uint32 length then bytes.
func stringOf(b []byte) []byte {
	var v struct{ S []byte }
	v.S = b
	return ssh.Marshal(&v)
}

// mpintOf returns ssh.Marshal's encoding of a single *big.Int field, which is
// the RFC 4251 "mpint" type.
func mpintOf(i *big.Int) []byte {
	var v struct{ I *big.Int }
	v.I = i
	return ssh.Marshal(&v)
}

// namelistOf returns ssh.Marshal's encoding of a []string field, which is the
// RFC 4251 "name-list" type.
func namelistOf(names []string) []byte {
	var v struct{ N []string }
	v.N = names
	return ssh.Marshal(&v)
}

func main() {
	out := flag.String("o", "tests/ssh_vectors.h", "output header")
	flag.Parse()

	var sb strings.Builder
	sb.WriteString(`/* SPDX-License-Identifier: BSD-3-Clause
 *
 * GENERATED by tools/genssh -- do not edit.
 *
 * Every "want" here is the output of golang.org/x/crypto/ssh, reached
 * through its exported API, rather than a value typed out from the RFC.
 * Regenerate with:
 *
 *     cd tools/genssh && GOFLAGS=-mod=mod go run . -o ../../tests/ssh_vectors.h
 */
#ifndef TC_SSH_VECTORS_H_
#define TC_SSH_VECTORS_H_

typedef struct {
	const char *name;
	const char *in;   /* hex, or ASCII where the test says so */
	const char *want; /* hex */
} tc_ssh_vector;

`)

	// ---- strings -----------------------------------------------------
	sb.WriteString("static const tc_ssh_vector kSshStringVectors[] = {\n")
	for _, s := range [][]byte{
		{},
		[]byte("a"),
		[]byte("ssh-ed25519"),
		[]byte("curve25519-sha256"),
		[]byte("chacha20-poly1305@openssh.com"),
		{0x00},
		{0x00, 0xff, 0x00},
		[]byte(strings.Repeat("x", 255)),
		[]byte(strings.Repeat("y", 256)),
	} {
		emit(&sb, fmt.Sprintf("string len %d", len(s)), hexs(s),
			hexs(stringOf(s)))
	}
	// A few random ones, so the fixed cases above are not the only shapes.
	rng := rand.New(rand.NewSource(7))
	for i := 0; i < 8; i++ {
		b := make([]byte, rng.Intn(300))
		rng.Read(b)
		emit(&sb, fmt.Sprintf("string random %d", i), hexs(b),
			hexs(stringOf(b)))
	}
	sb.WriteString("};\n\n")

	// ---- mpints ------------------------------------------------------
	//
	// The interesting cases are all about the minimal two's-complement form:
	// zero is empty, a leading zero byte appears only to clear a high bit,
	// and leading zeros in the input are dropped.
	sb.WriteString("static const tc_ssh_vector kSshMpintVectors[] = {\n")
	mpints := []string{
		"00",
		"01",
		"7f",
		"80",
		"ff",
		"0080",
		"000080",
		"0100",
		"7fffffff",
		"80000000",
		"ffffffffffffffff",
		"0000000000000000000000000000000000000000000000000000000000000001",
		"7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
		"8000000000000000000000000000000000000000000000000000000000000000",
		"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
	}
	for _, h := range mpints {
		b, err := hex.DecodeString(h)
		if err != nil {
			panic(err)
		}
		i := new(big.Int).SetBytes(b)
		emit(&sb, "mpint "+h, h, hexs(mpintOf(i)))
	}
	sb.WriteString("};\n\n")

	// ---- name-lists --------------------------------------------------
	sb.WriteString("static const tc_ssh_vector kSshNamelistVectors[] = {\n")
	for _, n := range [][]string{
		{},
		{"none"},
		{"curve25519-sha256", "curve25519-sha256@libssh.org"},
		{"ssh-ed25519"},
		{"chacha20-poly1305@openssh.com", "aes256-gcm@openssh.com"},
		{"a", "b", "c", "d"},
	} {
		emit(&sb, "namelist "+strings.Join(n, "|"),
			strings.Join(n, ","), hexs(namelistOf(n)))
	}
	sb.WriteString("};\n\n")

	// ---- ssh-ed25519 key and signature blobs -------------------------
	//
	// These are the two structures the exchange hash and userauth are built
	// over. A seed of fixed bytes keeps the output reproducible, which is
	// what lets diagnostic level 1 diff this file against a fresh run.
	sb.WriteString("static const struct {\n\tconst char *seed;\n" +
		"\tconst char *pub_blob;\n\tconst char *msg;\n" +
		"\tconst char *sig_blob;\n} kSshEd25519Vectors[] = {\n")
	for i := 0; i < 4; i++ {
		seed := make([]byte, ed25519.SeedSize)
		for j := range seed {
			seed[j] = byte(i*37 + j)
		}
		priv := ed25519.NewKeyFromSeed(seed)
		pub, err := ssh.NewPublicKey(priv.Public().(ed25519.PublicKey))
		if err != nil {
			panic(err)
		}
		signer, err := ssh.NewSignerFromKey(priv)
		if err != nil {
			panic(err)
		}
		msg := []byte(fmt.Sprintf("exchange hash %d", i))
		// Ed25519 is deterministic (RFC 8032), so this is reproducible even
		// though Sign takes a random source.
		sig, err := signer.Sign(nil, msg)
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&sb, "\t{ \"%s\", \"%s\", \"%s\", \"%s\" },\n",
			hexs(seed), hexs(pub.Marshal()), hexs(msg),
			hexs(ssh.Marshal(sig)))
	}
	sb.WriteString("};\n\n#endif /* TC_SSH_VECTORS_H_ */\n")

	if err := os.WriteFile(*out, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}
