// SPDX-License-Identifier: BSD-3-Clause

// Command genssh writes tests/ssh_vectors.h from golang.org/x/crypto/ssh and
// the standard library, which is the same choice genvectors makes and for the
// same reason: a hand-transcribed expected value is worse than no test,
// because it invites you to "fix" correct code to match it.
//
// What is anchored here is the wire encoding of RFC 4251 section 5 -- string,
// mpint and name-list -- plus the ssh-ed25519 public key and signature blobs.
// Those are the encodings that everything above them is hashed over, so a
// disagreement in any of them shows up as an exchange-hash mismatch and
// nothing more specific. They are worth pinning against the implementation we
// have to interoperate with rather than against a reading of the RFC.
//
// x/crypto/ssh keeps its marshalling helpers unexported, so the encodings are
// reached through the exported surfaces that use them: ssh.Marshal for
// structs, and ssh.NewPublicKey / Signer.Sign for the key blobs.
package main

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"math/big"
	"math/rand"
	"os"
	"strings"

	"encoding/binary"

	"golang.org/x/crypto/chacha20"
	"golang.org/x/crypto/poly1305"
	"golang.org/x/crypto/ssh"
)

// opensshPacket builds one chacha20-poly1305@openssh.com packet, following
// OpenSSH's PROTOCOL.chacha20poly1305 rather than RFC 8439 -- they are
// different constructions with confusingly similar names.
//
// The padding is passed in rather than generated so the output is
// reproducible; the real implementation must use random padding, because with
// a stream cipher a predictable tail leaks the payload length modulo the
// block size.
func opensshPacket(keyMat []byte, seq uint32, payload, pad []byte) []byte {
	// The first 32 bytes are K_2 and the second 32 are K_1. That order is
	// reversed from what the names suggest and is the single easiest thing
	// to get wrong here.
	k2, k1 := keyMat[0:32], keyMat[32:64]

	// The nonce is the sequence number as a big-endian uint64. OpenSSH uses
	// ChaCha20's original 64-bit-nonce form; x/crypto exposes RFC 8439's
	// 96-bit form, and the two agree when the leading four bytes are zero.
	nonce := make([]byte, 12)
	binary.BigEndian.PutUint64(nonce[4:], uint64(seq))

	region := make([]byte, 1+len(payload)+len(pad))
	region[0] = byte(len(pad))
	copy(region[1:], payload)
	copy(region[1+len(payload):], pad)

	out := make([]byte, 4+len(region)+16)
	binary.BigEndian.PutUint32(out[0:4], uint32(len(region)))

	// The length field gets its own key, so that reading it before the
	// packet is authenticated leaks nothing about the payload.
	c1, err := chacha20.NewUnauthenticatedCipher(k1, nonce)
	if err != nil {
		panic(err)
	}
	c1.XORKeyStream(out[0:4], out[0:4])

	c2, err := chacha20.NewUnauthenticatedCipher(k2, nonce)
	if err != nil {
		panic(err)
	}
	var polyKey [32]byte
	c2.XORKeyStream(polyKey[:], polyKey[:])
	// SetCounter, not "keep going": the Poly1305 key takes only 32 bytes of
	// block zero and the rest of that block is discarded. Continuing from
	// byte 32 would encrypt the payload with the wrong half of a block.
	c2.SetCounter(1)
	c2.XORKeyStream(out[4:4+len(region)], region)

	// Encrypt-then-MAC, over the encrypted length field as well.
	var tag [16]byte
	poly1305.Sum(&tag, out[0:4+len(region)], &polyKey)
	copy(out[4+len(region):], tag[:])
	return out
}

func hexs(b []byte) string { return hex.EncodeToString(b) }

// emit writes one vector as a C string pair.
func emit(sb *strings.Builder, name, in, want string) {
	fmt.Fprintf(sb, "\t{ \"%s\", \"%s\", \"%s\" },\n", name, in, want)
}

// --- string -----------------------------------------------------------

// stringOf returns ssh.Marshal's encoding of a single []byte field, which is
// exactly the RFC 4251 "string" type: uint32 length then bytes.
func stringOf(b []byte) []byte {
	var v struct{ S []byte }
	v.S = b
	return ssh.Marshal(&v)
}

// mpintOf returns ssh.Marshal's encoding of a single *big.Int field, which is
// the RFC 4251 "mpint" type.
func mpintOf(i *big.Int) []byte {
	var v struct{ I *big.Int }
	v.I = i
	return ssh.Marshal(&v)
}

// namelistOf returns ssh.Marshal's encoding of a []string field, which is the
// RFC 4251 "name-list" type.
func namelistOf(names []string) []byte {
	var v struct{ N []string }
	v.N = names
	return ssh.Marshal(&v)
}

func main() {
	out := flag.String("o", "tests/ssh_vectors.h", "output header")
	flag.Parse()

	var sb strings.Builder
	sb.WriteString(`/* SPDX-License-Identifier: BSD-3-Clause
 *
 * GENERATED by tools/genssh -- do not edit.
 *
 * Every "want" here is the output of golang.org/x/crypto/ssh, reached
 * through its exported API, rather than a value typed out from the RFC.
 * Regenerate with:
 *
 *     cd tools/genssh && GOFLAGS=-mod=mod go run . -o ../../tests/ssh_vectors.h
 */
#ifndef TC_SSH_VECTORS_H_
#define TC_SSH_VECTORS_H_

typedef struct {
	const char *name;
	const char *in;   /* hex, or ASCII where the test says so */
	const char *want; /* hex */
} tc_ssh_vector;

`)

	// ---- strings -----------------------------------------------------
	sb.WriteString("static const tc_ssh_vector kSshStringVectors[] = {\n")
	for _, s := range [][]byte{
		{},
		[]byte("a"),
		[]byte("ssh-ed25519"),
		[]byte("curve25519-sha256"),
		[]byte("chacha20-poly1305@openssh.com"),
		{0x00},
		{0x00, 0xff, 0x00},
		[]byte(strings.Repeat("x", 255)),
		[]byte(strings.Repeat("y", 256)),
	} {
		emit(&sb, fmt.Sprintf("string len %d", len(s)), hexs(s),
			hexs(stringOf(s)))
	}
	// A few random ones, so the fixed cases above are not the only shapes.
	rng := rand.New(rand.NewSource(7))
	for i := 0; i < 8; i++ {
		b := make([]byte, rng.Intn(300))
		rng.Read(b)
		emit(&sb, fmt.Sprintf("string random %d", i), hexs(b),
			hexs(stringOf(b)))
	}
	sb.WriteString("};\n\n")

	// ---- mpints ------------------------------------------------------
	//
	// The interesting cases are all about the minimal two's-complement form:
	// zero is empty, a leading zero byte appears only to clear a high bit,
	// and leading zeros in the input are dropped.
	sb.WriteString("static const tc_ssh_vector kSshMpintVectors[] = {\n")
	mpints := []string{
		"00",
		"01",
		"7f",
		"80",
		"ff",
		"0080",
		"000080",
		"0100",
		"7fffffff",
		"80000000",
		"ffffffffffffffff",
		"0000000000000000000000000000000000000000000000000000000000000001",
		"7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
		"8000000000000000000000000000000000000000000000000000000000000000",
		"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
	}
	for _, h := range mpints {
		b, err := hex.DecodeString(h)
		if err != nil {
			panic(err)
		}
		i := new(big.Int).SetBytes(b)
		emit(&sb, "mpint "+h, h, hexs(mpintOf(i)))
	}
	sb.WriteString("};\n\n")

	// ---- name-lists --------------------------------------------------
	sb.WriteString("static const tc_ssh_vector kSshNamelistVectors[] = {\n")
	for _, n := range [][]string{
		{},
		{"none"},
		{"curve25519-sha256", "curve25519-sha256@libssh.org"},
		{"ssh-ed25519"},
		{"chacha20-poly1305@openssh.com", "aes256-gcm@openssh.com"},
		{"a", "b", "c", "d"},
	} {
		emit(&sb, "namelist "+strings.Join(n, "|"),
			strings.Join(n, ","), hexs(namelistOf(n)))
	}
	sb.WriteString("};\n\n")

	// ---- ssh-ed25519 key and signature blobs -------------------------
	//
	// These are the two structures the exchange hash and userauth are built
	// over. A seed of fixed bytes keeps the output reproducible, which is
	// what lets diagnostic level 1 diff this file against a fresh run.
	sb.WriteString("static const struct {\n\tconst char *seed;\n" +
		"\tconst char *pub_blob;\n\tconst char *msg;\n" +
		"\tconst char *sig_blob;\n} kSshEd25519Vectors[] = {\n")
	for i := 0; i < 4; i++ {
		seed := make([]byte, ed25519.SeedSize)
		for j := range seed {
			seed[j] = byte(i*37 + j)
		}
		priv := ed25519.NewKeyFromSeed(seed)
		pub, err := ssh.NewPublicKey(priv.Public().(ed25519.PublicKey))
		if err != nil {
			panic(err)
		}
		signer, err := ssh.NewSignerFromKey(priv)
		if err != nil {
			panic(err)
		}
		msg := []byte(fmt.Sprintf("exchange hash %d", i))
		// Ed25519 is deterministic (RFC 8032), so this is reproducible even
		// though Sign takes a random source.
		sig, err := signer.Sign(nil, msg)
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&sb, "\t{ \"%s\", \"%s\", \"%s\", \"%s\" },\n",
			hexs(seed), hexs(pub.Marshal()), hexs(msg),
			hexs(ssh.Marshal(sig)))
	}
	sb.WriteString("};\n\n")

	// ---- chacha20-poly1305@openssh.com packets -----------------------
	//
	// Whole packets, so decoding one of these checks the key split, the
	// nonce, both counters, the MAC coverage and the framing at once --
	// any of which being wrong makes the tag fail.
	sb.WriteString("static const struct {\n\tconst char *key;\n" +
		"\tunsigned seq;\n\tconst char *payload;\n" +
		"\tconst char *packet;\n} kSshPacketVectors[] = {\n")
	prng := rand.New(rand.NewSource(11))
	for i, plen := range []int{0, 1, 5, 6, 7, 8, 9, 63, 64, 65, 255, 1024} {
		keyMat := make([]byte, 64)
		for j := range keyMat {
			keyMat[j] = byte(i*13 + j*7)
		}
		payload := make([]byte, plen)
		prng.Read(payload)

		// The same rule the C side uses: the length field is excluded from
		// the alignment, because it is encrypted separately.
		padLen := 8 - ((1 + plen) % 8)
		if padLen < 4 {
			padLen += 8
		}
		pad := make([]byte, padLen)
		prng.Read(pad)

		seq := uint32(i * 4099)
		pkt := opensshPacket(keyMat, seq, payload, pad)
		fmt.Fprintf(&sb, "\t{ \"%s\", %d, \"%s\", \"%s\" },\n",
			hexs(keyMat), seq, hexs(payload), hexs(pkt))
	}
	sb.WriteString("};\n\n")

	// ---- exchange hash and key derivation ----------------------------
	//
	// H is built from the field encodings ssh.Marshal produces, composed per
	// RFC 8731 section 3. The encodings are x/crypto's; the composition is
	// read from the RFC, the same as the C. So this pins the part most
	// likely to be wrong -- K is an mpint where the two public keys are
	// strings, which is worth about half of all secrets going wrong if
	// missed -- while the live test against OpenSSH settles the rest.
	sb.WriteString("static const struct {\n\tconst char *vc;\n" +
		"\tconst char *vs;\n\tconst char *ic;\n\tconst char *is;\n" +
		"\tconst char *ks;\n\tconst char *qc;\n\tconst char *qs;\n" +
		"\tconst char *secret;\n\tconst char *h;\n" +
		"\tconst char *c2s;\n\tconst char *s2c;\n" +
		"} kSshKexVectors[] = {\n")
	krng := rand.New(rand.NewSource(23))
	for i := 0; i < 6; i++ {
		vc := []byte(fmt.Sprintf("SSH-2.0-client_%d", i))
		vs := []byte(fmt.Sprintf("SSH-2.0-tailcatc_%d", i))
		ic := make([]byte, 40+krng.Intn(80))
		is := make([]byte, 40+krng.Intn(80))
		ks := make([]byte, 51)
		qc := make([]byte, 32)
		qs := make([]byte, 32)
		secret := make([]byte, 32)
		krng.Read(ic)
		krng.Read(is)
		krng.Read(ks)
		krng.Read(qc)
		krng.Read(qs)
		krng.Read(secret)
		// Half the cases with the top bit of K set, which is the case the
		// mpint rule exists for: it needs a leading zero byte and a string
		// encoding would not add one.
		if i%2 == 0 {
			secret[0] |= 0x80
		} else {
			secret[0] &^= 0x80
		}

		var buf []byte
		str := func(b []byte) {
			var v struct{ S []byte }
			v.S = b
			buf = append(buf, ssh.Marshal(&v)...)
		}
		str(vc)
		str(vs)
		str(ic)
		str(is)
		str(ks)
		str(qc)
		str(qs)
		var mp struct{ I *big.Int }
		mp.I = new(big.Int).SetBytes(secret)
		buf = append(buf, ssh.Marshal(&mp)...)

		h := sha256.Sum256(buf)

		// RFC 4253 7.2, extended to 64 bytes because SHA-256 gives 32 and
		// chacha20-poly1305 wants 64.
		derive := func(letter byte) []byte {
			kEnc := ssh.Marshal(&mp)
			d1 := sha256.New()
			d1.Write(kEnc)
			d1.Write(h[:])
			d1.Write([]byte{letter})
			d1.Write(h[:]) // session id == H on the first exchange
			k1 := d1.Sum(nil)
			d2 := sha256.New()
			d2.Write(kEnc)
			d2.Write(h[:])
			d2.Write(k1)
			k2 := d2.Sum(nil)
			return append(append([]byte{}, k1...), k2...)
		}

		fmt.Fprintf(&sb,
			"\t{ \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\" },\n",
			hexs(vc), hexs(vs), hexs(ic), hexs(is), hexs(ks), hexs(qc),
			hexs(qs), hexs(secret), hexs(h[:]), hexs(derive('C')),
			hexs(derive('D')))
	}
	sb.WriteString("};\n\n")

	sb.WriteString("#endif /* TC_SSH_VECTORS_H_ */\n")

	if err := os.WriteFile(*out, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}
