#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Generate src/usage_text.c from doc/usage.md.

`tailcat-c readme` prints a usage document, as upstream's does. Upstream
embeds its own README.md; ours is a fuller manual, opening with what the port
does not do, so a shorter file is embedded instead. Someone who typed `readme`
at a terminal wants the examples, not the caveats.

The generated file is committed, so a build needs no Python. Level 1 checks it
against its source, the same way the crypto and SSH vectors are checked.
"""
import io
import os
import sys

SRC = 'doc/usage.md'
DST = 'src/usage_text.c'


def c_escape(line):
    out = []
    for ch in line:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\t':
            out.append('\\t')
        elif ord(ch) < 0x20 or ord(ch) == 0x7f:
            out.append('\\%03o' % ord(ch))
        else:
            out.append(ch)
    return ''.join(out)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    text = io.open(SRC, encoding='utf-8').read()

    # A stray CR would reach a terminal as one, so normalise here rather than
    # relying on however the file was checked out.
    text = text.replace('\r\n', '\n').replace('\r', '\n')

    # Every other byte this program prints is ASCII, and the six operating
    # systems it runs on do not agree about what a terminal does with the
    # rest. An em dash that arrives as two mojibake bytes is a worse
    # document than one written with two hyphens, so refuse rather than
    # guess.
    bad = sorted({c for c in text if ord(c) > 0x7f})
    if bad:
        sys.stderr.write('%s: non-ASCII %s -- write it in ASCII\n'
                         % (SRC, ' '.join('U+%04X' % ord(c) for c in bad)))
        return 1

    parts = [
        '/* SPDX-License-Identifier: BSD-3-Clause */',
        '/*',
        ' * GENERATED by scripts/gen-usage.py from doc/usage.md -- do not edit.',
        ' *',
        ' * What `tailcat-c readme` prints. README.md is not this: it is the',
        ' * full manual, and PORT.md is the engineering record behind it.',
        ' * Embedding either would add to a binary whose size is a selling',
        ' * point, to answer a question nobody typing `readme` asked.',
        ' */',
        '',
        '#include "tc/tailcat.h"',
        '',
        '/* ISO C99 guarantees only 4095-byte string literals and -Wpedantic',
        ' * says so; the same exception src/net/ca_bundle.c takes, for the same',
        ' * reason. */',
        '#pragma GCC diagnostic ignored "-Woverlength-strings"',
        '',
        'const char tc_usage_text[] =',
    ]
    for line in text.split('\n'):
        parts.append('\t"%s\\n"' % c_escape(line))
    parts.append('\t;')
    parts.append('')

    out = '\n'.join(parts)
    io.open(DST, 'w', encoding='utf-8', newline='\n').write(out)
    sys.stderr.write('wrote %s (%d bytes of text)\n' % (DST, len(text)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
