#!/usr/bin/env python3
"""Regenerate src/net/ca_bundle.c from a PEM CA bundle.

An Actually Portable Executable cannot rely on the host's trust store: the
paths differ per operating system and may not exist at all, and the whole
point of the binary is that it runs anywhere unchanged. So the roots are
compiled in.

Usage:
    curl -fsSLo cacert.pem https://curl.se/ca/cacert.pem
    python3 scripts/gen-ca-bundle.py cacert.pem src/net/ca_bundle.c
"""
import datetime
import re
import sys

BEGIN = "-----BEGIN CERTIFICATE-----"
END = "-----END CERTIFICATE-----"

# Emitted as one C string literal per PEM line. PEM bodies are base64 plus the
# two delimiter lines, so the only character needing escaping is the quote;
# there are no backslashes in well-formed PEM. We escape both anyway rather
# than trust the input.
BACKSLASH = chr(92)


def escape(line: str) -> str:
    return line.replace(BACKSLASH, BACKSLASH * 2).replace('"', BACKSLASH + '"')


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]

    with open(src, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()

    certs = re.findall(
        re.escape(BEGIN) + ".*?" + re.escape(END) + chr(10), text, re.S
    )
    if not certs:
        print("gen-ca-bundle: no certificates found", file=sys.stderr)
        return 1

    blob = "".join(certs)

    nl = BACKSLASH + "n"  # the two characters a C string needs
    lines = [
        "/* SPDX-License-Identifier: BSD-3-Clause */",
        "/*",
        " * GENERATED by scripts/gen-ca-bundle.py -- do not edit.",
        " *",
        " * Mozilla's CA root bundle, as distributed by the curl project.",
        " * Compiled in because an Actually Portable Executable cannot rely on",
        " * the host's trust store existing at a known path, or at all.",
        " *",
        " * %d roots, generated %s."
        % (len(certs), datetime.date.today().isoformat()),
        " */",
        "",
        '#include "tc/tls.h"',
        "",
        "/* ISO C99 only requires compilers to support 4095-byte string",
        " * literals, and -Wpedantic says so. GCC and Clang both handle this",
        " * fine, and the alternative -- a 181KB hex byte array -- is a far",
        " * larger and less readable source file for no benefit. */",
        '#pragma GCC diagnostic ignored "-Woverlength-strings"',
        "",
        "const size_t tc_ca_bundle_count = %d;" % len(certs),
        "",
        "const char tc_ca_bundle_pem[] =",
    ]
    for line in blob.split(chr(10)):
        if line == "":
            continue
        lines.append('\t"%s%s"' % (escape(line), nl))
    lines += [
        "\t;",
        "",
        "/* sizeof, not strlen: mbedtls_x509_crt_parse requires the terminating",
        " * NUL to be counted in the length for PEM input. */",
        "const size_t tc_ca_bundle_pem_len = sizeof tc_ca_bundle_pem;",
        "",
    ]

    with open(dst, "w", encoding="utf-8", newline=chr(10)) as f:
        f.write(chr(10).join(lines))

    print(
        "gen-ca-bundle: wrote %s (%d roots, %d bytes PEM)"
        % (dst, len(certs), len(blob))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
