#!/bin/sh
# Run the test suite on the aarch64 half, under qemu-user.
#
# The aarch64 half of every binary is built, linked and checked for presence
# by check-fat.sh -- and until this script it had never been *executed*. That
# made it the largest untested claim in the project: half of what ships, on
# the strength of "it compiled".
#
# The plan in the README assumed this would need `assimilate` to flatten an
# APE into a plain ELF first. It does not. cosmocc already leaves a plain
# statically-linked aarch64 ELF beside each APE as `<name>.aarch64.elf`, and
# qemu-user runs those directly -- no APE loader, no binfmt registration, no
# assimilation.
#
# What this does and does not prove: it exercises real aarch64 instructions
# generated by the real compiler, so it catches miscompilation and
# arch-dependent arithmetic. It runs them against a translated syscall layer
# rather than a real aarch64 kernel, so it does not exercise Cosmopolitan's
# own aarch64 runtime as hardware would. That is the next rung up.
set -eu

BUILD="${BUILD:-build/cosmo}"

QEMU=""
for candidate in qemu-aarch64-static qemu-aarch64; do
	if command -v "$candidate" > /dev/null 2>&1; then
		QEMU="$candidate"
		break
	fi
done

if [ -z "$QEMU" ]; then
	cat >&2 <<'EOF'
test-aarch64: no qemu-aarch64 found, so the aarch64 half stayed untested.

  sudo apt install qemu-user-static      # Debian/Ubuntu, including WSL
  sudo dnf install qemu-user-static      # Fedora

Nothing else is needed: cosmocc already emits a plain aarch64 ELF beside
each binary, so there is no APE loader or binfmt registration involved.
EOF
	exit 2
fi
echo "using $QEMU"

found=0
failed=0
for elf in "$BUILD"/test_*.aarch64.elf; do
	[ -e "$elf" ] || continue
	found=$((found + 1))
	name=$(basename "$elf" .aarch64.elf)
	if out=$("$QEMU" "$elf" 2>&1); then
		printf '%s\n' "$out" | tail -1
	else
		failed=$((failed + 1))
		echo "FAIL $name" >&2
		printf '%s\n' "$out" | tail -20 >&2
	fi
done

if [ "$found" -eq 0 ]; then
	echo "test-aarch64: no aarch64 ELFs in $BUILD -- run make first" >&2
	exit 1
fi

echo
if [ "$failed" -ne 0 ]; then
	echo "FAIL aarch64: $failed of $found test binaries failed" >&2
	exit 1
fi
echo "ok   aarch64                  $found test binaries, on real aarch64 instructions"
