#!/usr/bin/env python3
"""Generate tests/sshauth_vectors.h: real publickey requests, made elsewhere.

A round-trip test signs with the same library that verifies, so it agrees with
itself about anything it gets wrong -- and everything interesting here is a
question of format rather than of arithmetic. RFC 8332 has a client offer a key
whose blob says `ssh-rsa` while signing under `rsa-sha2-256`; an ECDSA
signature is two integers inside a string inside a blob; the message being
signed is eight length-prefixed fields that must be rebuilt byte for byte. Get
any of that wrong in both directions at once and a round trip still passes.

So the keys come from `ssh-keygen` and the signatures from `openssl`, and this
program only assembles what RFC 4252 section 7 says the wire looks like. The
private halves live in a temporary directory and are deleted; what lands in the
repository is public keys and signatures over a fixed session id, which
authenticate nobody anywhere.

Run from the repository root, on a machine with ssh-keygen and openssl:

    python3 tools/gen-sshauth-vectors.py

Regenerating is not necessary and not routine -- the vectors are golden. It is
here so they can be checked, and so a new algorithm can be added to the list
below rather than assembled by hand.
"""
import base64
import os
import shutil
import struct
import subprocess
import sys
import tempfile

OUT = 'tests/sshauth_vectors.h'

# The session id every vector is signed over. Fixed, because a vector has to
# be reproducible, and arbitrary, because the real one is a hash of two
# ephemeral keys and has no structure to imitate.
SID = bytes((i * 7 + 3) & 0xff for i in range(32))

USER = 'vector'
SERVICE = 'ssh-connection'

MSG_USERAUTH_REQUEST = 50

# (name, ssh-keygen -t, ssh-keygen -b, signature algorithm, openssl digest)
KEYS = [
    ('rsa2048_sha256', 'rsa', 2048, 'rsa-sha2-256', 'sha256'),
    ('rsa2048_sha512', 'rsa', 2048, 'rsa-sha2-512', 'sha512'),
    ('nistp256', 'ecdsa', 256, 'ecdsa-sha2-nistp256', 'sha256'),
    ('nistp384', 'ecdsa', 384, 'ecdsa-sha2-nistp384', 'sha384'),
    ('ed25519', 'ed25519', None, 'ssh-ed25519', None),
]


def sstr(b):
    """An SSH string: uint32 length, then the bytes."""
    return struct.pack('>I', len(b)) + b


def cstr(s):
    return sstr(s.encode('ascii'))


def mpint(b):
    """An SSH mpint from DER INTEGER content, which is already minimal
    two's-complement big-endian -- the same encoding."""
    return sstr(b)


def der_sig_to_ssh(der):
    """openssl writes ECDSA signatures as SEQUENCE { INTEGER r, INTEGER s };
    SSH wants the two as mpints inside a string of their own."""
    assert der[0] == 0x30, 'not a DER SEQUENCE'
    i = 2
    if der[1] & 0x80:
        i = 2 + (der[1] & 0x7f)
    out = b''
    for _ in range(2):
        assert der[i] == 0x02, 'not a DER INTEGER'
        n = der[i + 1]
        assert n < 0x80, 'long-form INTEGER length'
        out += mpint(der[i + 2:i + 2 + n])
        i += 2 + n
    return out


def run(args, **kw):
    return subprocess.run(args, check=True, capture_output=True, **kw)


def generate(tmp, name, keytype, bits, algo, digest):
    path = os.path.join(tmp, name)
    args = ['ssh-keygen', '-q', '-t', keytype, '-N', '', '-C',
            name + '@vector', '-f', path]
    if bits is not None:
        args[4:4] = ['-b', str(bits)]
    run(args)

    with open(path + '.pub') as f:
        publine = f.read().strip()
    fields = publine.split()
    keyblob = base64.b64decode(fields[1])

    # PEM, because openssl does not read OpenSSH's own private key format.
    # ed25519 has no PEM form in ssh-keygen, so it is generated by openssl
    # instead and the SSH public blob rebuilt from the raw key.
    if keytype == 'ed25519':
        pem = os.path.join(tmp, name + '.pem')
        run(['openssl', 'genpkey', '-algorithm', 'ed25519', '-out', pem])
        der = run(['openssl', 'pkey', '-in', pem, '-pubout',
                   '-outform', 'DER']).stdout
        raw = der[-32:]
        keyblob = cstr('ssh-ed25519') + sstr(raw)
        publine = 'ssh-ed25519 ' + \
            base64.b64encode(keyblob).decode('ascii') + ' ' + name + '@vector'
    else:
        run(['ssh-keygen', '-q', '-p', '-N', '', '-m', 'PEM', '-f', path])
        pem = path

    # RFC 4252 section 7: what the client signs.
    signed = (sstr(SID) + bytes([MSG_USERAUTH_REQUEST]) + cstr(USER) +
              cstr(SERVICE) + cstr('publickey') + b'\x01' + cstr(algo) +
              sstr(keyblob))

    msgfile = os.path.join(tmp, name + '.msg')
    with open(msgfile, 'wb') as f:
        f.write(signed)
    if digest is None:
        # ed25519 signs the message itself; there is no separate digest.
        raw_sig = run(['openssl', 'pkeyutl', '-sign', '-inkey', pem,
                       '-rawin', '-in', msgfile]).stdout
    else:
        raw_sig = run(['openssl', 'dgst', '-' + digest, '-sign', pem,
                       msgfile]).stdout

    if algo.startswith('ecdsa-'):
        sigblob = cstr(algo) + sstr(der_sig_to_ssh(raw_sig))
    else:
        sigblob = cstr(algo) + sstr(raw_sig)

    payload = (bytes([MSG_USERAUTH_REQUEST]) + cstr(USER) + cstr(SERVICE) +
               cstr('publickey') + b'\x01' + cstr(algo) + sstr(keyblob) +
               sstr(sigblob))

    return {'name': name, 'algo': algo, 'publine': publine,
            'keyblob': keyblob, 'payload': payload}


def carray(name, data):
    lines = ['static const uint8_t %s[] = {' % name]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append('\t' + ' '.join('0x%02x,' % b for b in chunk))
    lines.append('};')
    return '\n'.join(lines)


def main():
    for tool in ('ssh-keygen', 'openssl'):
        if shutil.which(tool) is None:
            sys.exit('%s is needed to generate the vectors' % tool)

    tmp = tempfile.mkdtemp(prefix='sshauth-vectors-')
    try:
        vs = [generate(tmp, *k) for k in KEYS]
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    out = []
    out.append('/* SPDX-License-Identifier: BSD-3-Clause\n'
               ' *\n'
               ' * Generated by tools/gen-sshauth-vectors.py -- do not edit.\n'
               ' *\n'
               ' * Real SSH publickey authentication requests: keys from\n'
               ' * ssh-keygen, signatures from openssl, framing per RFC 4252\n'
               ' * section 7. Nothing here is secret -- the private halves were\n'
               ' * made in a temporary directory and destroyed -- and every\n'
               ' * signature is over the one fixed session id below, so none of\n'
               ' * them authenticates anything anywhere.\n'
               ' *\n'
               ' * They exist because a test that signs with the same library\n'
               ' * that verifies agrees with itself about any format it gets\n'
               ' * wrong, and format is all this code is.\n'
               ' */\n'
               '#ifndef TC_SSHAUTH_VECTORS_H_\n'
               '#define TC_SSHAUTH_VECTORS_H_\n\n'
               '#include <stddef.h>\n'
               '#include <stdint.h>\n\n'
               'typedef struct {\n'
               '\tconst char *name;\n'
               '\tconst char *algo;\n'
               '\tconst char *authorized_line;\n'
               '\tconst uint8_t *keyblob;\n'
               '\tsize_t keyblob_len;\n'
               '\tconst uint8_t *payload;\n'
               '\tsize_t payload_len;\n'
               '} tc_sshauth_vector;\n')
    out.append('#define TC_SSHAUTH_VECTOR_USER "%s"' % USER)
    out.append('#define TC_SSHAUTH_VECTOR_SERVICE "%s"\n' % SERVICE)
    out.append(carray('tc_sshauth_vector_sid', SID) + '\n')

    for v in vs:
        out.append(carray('vec_%s_key' % v['name'], v['keyblob']))
        out.append(carray('vec_%s_msg' % v['name'], v['payload']) + '\n')

    out.append('static const tc_sshauth_vector tc_sshauth_vectors[] = {')
    for v in vs:
        # The public key line is long; split it so the file stays readable.
        line = v['publine']
        parts = [line[i:i + 60] for i in range(0, len(line), 60)]
        lit = '\n\t\t '.join('"%s"' % p for p in parts)
        out.append('\t{\n'
                   '\t\t"%s",\n'
                   '\t\t"%s",\n'
                   '\t\t%s,\n'
                   '\t\tvec_%s_key, sizeof vec_%s_key,\n'
                   '\t\tvec_%s_msg, sizeof vec_%s_msg,\n'
                   '\t},' % (v['name'], v['algo'], lit, v['name'],
                             v['name'], v['name'], v['name']))
    out.append('};\n')
    out.append('static const size_t tc_sshauth_num_vectors =\n'
               '    sizeof tc_sshauth_vectors / sizeof tc_sshauth_vectors[0];'
               '\n\n#endif /* TC_SSHAUTH_VECTORS_H_ */')

    with open(OUT, 'w', newline='\n') as f:
        f.write('\n'.join(out) + '\n')
    print('wrote %s (%d vectors)' % (OUT, len(vs)))


if __name__ == '__main__':
    main()
