/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Saved identities: the `*.private.json` files `genkey` writes.
 *
 * Without one, every run mints a fresh identity and a server's address changes
 * on every restart, which makes it useless in a script or a service file. A
 * saved key is what turns tailcat from a one-shot into something with a
 * stable address.
 *
 * The format is upstream's, tab-indented, and is read and written here byte
 * for byte compatibly -- a key generated by `tailcat genkey` works with
 * `tailcat-c` and the reverse:
 *
 *     {
 *         "Private": "privkey:<64 hex>",
 *         "Public": {
 *             "ServerPublic": "nodekey:<64 hex>",
 *             "ServerDiscoPublic": "discokey:<64 hex>",
 *             "PresharedKey": "psk:<64 hex>",
 *             "RegionID": 301
 *         }
 *     }
 *
 * The type prefixes are not decoration: they are how Tailscale's key types
 * marshal themselves, and a file without them is not one of these.
 *
 * Despite the name, `Public` holds the pre-shared key, which is a secret. The
 * whole file is secret, and is written 0600 for that reason.
 */
#ifndef TC_KEYFILE_H_
#define TC_KEYFILE_H_

#include "tc/addr.h"

typedef struct {
	uint8_t private_key[TC_NODE_KEY_LEN];
	bool has_private;
	/* Everything a client needs to reach this node, which is also exactly
	 * what the address encodes. */
	tc_conn_info pub;
} tc_keyfile;

/* tc_keyfile_parse reads one. The disco key is checked against the private
 * key rather than trusted: it is derived, so a file claiming a different one
 * is either corrupt or lying. */
int tc_keyfile_parse(tc_keyfile *k, const char *json, size_t len);

/* tc_keyfile_format writes one, matching upstream's layout so that a
 * diff between a file we wrote and one it wrote shows only the keys. */
int tc_keyfile_format(char *out, size_t cap, size_t *out_len,
                      const tc_keyfile *k);

/* tc_keyfile_generate makes a fresh identity: a random private key, its
 * derived public and disco keys, and a random pre-shared key unless psk is
 * false. region_id may be 0 for a client key, which has no region. */
int tc_keyfile_generate(tc_keyfile *k, bool psk, int64_t region_id);

/* tc_keyfile_error_string describes the last failure on this thread. */
const char *tc_keyfile_error_string(void);

/* tc_key_format_hex writes "<prefix>:<64 hex>", the way these keys print. */
int tc_key_format_hex(char *out, size_t cap, const char *prefix,
                      const uint8_t key[32]);

#endif /* TC_KEYFILE_H_ */
