/* SPDX-License-Identifier: BSD-3-Clause
 *
 * A minimal TLS client and the byte-stream abstraction the DERP client reads
 * and writes through.
 *
 * DERP runs over HTTPS. Note that TLS is defence in depth here, not the thing
 * that keeps tailcat traffic private: a DERP relay is untrusted by design and
 * only ever sees WireGuard-encrypted packets it cannot read. That is not a
 * reason to verify certificates loosely, though -- a relay that can be
 * impersonated can still deny service or fingerprint peers -- so verification
 * is required by default and can only be disabled explicitly.
 */
#ifndef TC_TLS_H_
#define TC_TLS_H_

#include "tc/tc.h"

/* ---- byte-stream transport ------------------------------------------- */

/* tc_stream is a blocking, ordered byte stream: either a plain TCP socket or
 * a TLS session over one. The DERP client is written against this so it can
 * be driven by a test harness with no network at all. */
typedef struct tc_stream tc_stream;

struct tc_stream {
	/* read_some reads at least one and at most len bytes, storing the count
	 * in *nread. It returns TC_ERR_TRUNC at end of stream. */
	int (*read_some)(tc_stream *s, uint8_t *buf, size_t len, size_t *nread);
	/* write_all writes every byte or fails. */
	int (*write_all)(tc_stream *s, const uint8_t *buf, size_t len);
	/* set_read_timeout bounds how long a read waits before returning
	 * TC_ERR_TIMEOUT. 0 means wait indefinitely. May be NULL on transports
	 * that cannot do it. */
	int (*set_read_timeout)(tc_stream *s, int ms);
	void (*close)(tc_stream *s);
	void *ctx;
};

/* tc_stream_set_read_timeout bounds subsequent reads on s.
 *
 * A timed-out read is recoverable rather than fatal: for TLS the record layer
 * keeps whatever it had, so a later read resumes mid-record cleanly. That is
 * what lets a caller poll for one thing while another is still in flight,
 * which is exactly what the meow exchange needs -- DERP delivery is best
 * effort, so the ping has to be resent while waiting for the ack. */
int tc_stream_set_read_timeout(tc_stream *s, int ms);

/* tc_stream_read_full reads exactly len bytes, looping over short reads.
 * Returns TC_ERR_TRUNC if the stream ends first. */
int tc_stream_read_full(tc_stream *s, uint8_t *buf, size_t len);

/* ---- TCP ------------------------------------------------------------- */

/* tc_tcp_connect opens a TCP connection to host:port.
 *
 * host may be a name or a literal IPv4 or IPv6 address; both address families
 * are tried in the order the resolver returns them. timeout_ms bounds the
 * whole attempt including resolution, and 0 means the system default. */
int tc_tcp_connect(tc_stream *out, const char *host, uint16_t port,
                   int timeout_ms);

/* ---- TLS ------------------------------------------------------------- */

typedef struct {
	/* Name to verify the certificate against and to send in SNI. Required
	 * unless verification is disabled. */
	const char *server_name;

	/* Setting this to true disables certificate verification entirely. It
	 * exists for testing against a DERP server with a self-signed
	 * certificate (upstream's DERPNode.InsecureForTests). Never set it
	 * because verification is inconvenient. */
	bool insecure_skip_verify;

	/* Optional extra roots in PEM form, in addition to the compiled-in
	 * bundle; NULL to use only the compiled-in roots. */
	const char *extra_ca_pem;
	size_t extra_ca_pem_len;
} tc_tls_config;

/* tc_tls_client wraps an established TCP stream in TLS and performs the
 * handshake. On success it takes ownership of `tcp`: closing the returned
 * stream closes the underlying socket. On failure `tcp` is left untouched for
 * the caller to close.
 *
 * *out and *tcp must not be the same object. */
int tc_tls_client(tc_stream *out, tc_stream *tcp, const tc_tls_config *cfg);

/* tc_tls_error_string returns a short description of the last TLS failure on
 * this thread, or "" if there is none. Useful because a handshake failure has
 * many distinguishable causes and TC_ERR_INVAL alone is unhelpful. */
const char *tc_tls_error_string(void);

/* ---- compiled-in roots ----------------------------------------------- */

/* Mozilla's CA bundle, generated by scripts/gen-ca-bundle.py. The length
 * includes the terminating NUL, which mbedtls_x509_crt_parse requires to be
 * counted for PEM input. */
extern const char tc_ca_bundle_pem[];
extern const size_t tc_ca_bundle_pem_len;
extern const size_t tc_ca_bundle_count;

#endif /* TC_TLS_H_ */
